package iT_Edit_Ex_Release;

import org.testng.annotations.AfterClass;

import org.testng.annotations.BeforeClass;
import org.testng.annotations.Parameters;
import org.testng.annotations.Test;

import FunctionLibrary.Common;

import com.thoughtworks.selenium.DefaultSelenium;
import com.thoughtworks.selenium.SeleneseTestBase;
import com.thoughtworks.selenium.Selenium;

@Test
public class CopyOfGrid_EditExRelease extends SeleneseTestBase{
    Selenium selenium;

    @BeforeClass	
    @Parameters({ "selenium.host","selenium.port","selenium.browser","selenium.url" })
    public void beforeClass(String host, String port, String browser, String url) {
        this.selenium = new DefaultSelenium(host, Integer.parseInt(port),
                browser, url);
        this.selenium.start();
        this.selenium.open("/oa/please_login.php");
        this.selenium.windowMaximize();
        System.out.println("Test Begins");
    }

    @AfterClass
    public void afterClass() {
        this.selenium.close();
        this.selenium.stop();

    }

    @Parameters({ "searchCriteria" })
    public void testGoogleSearch(String criteria) throws Exception {
    	System.out.println("userlogin start");
        
        
        //  Login   
  		Thread.sleep(7000);
  		selenium.type("name=username", "synergy");
  		Thread.sleep(2000);
  		selenium.type("name=password", "Orchard09");
  		Thread.sleep(2000);
  		selenium.clickAt("//input[@type='submit']", "");
  		Thread.sleep(20579);
  		verifyTrue(selenium.isElementPresent("id=contentArea"));
  		verifyTrue(selenium.isElementPresent("css=input[name=\"varSearchString\"]"));
  		System.out.println("userlogin end");

  	// 	OpenRelease
  		System.out.println("OpenRelease start");

  		Thread.sleep(10000);
  		verifyTrue(selenium.isElementPresent("css=input[name=\"varSearchString\"]"));
  		selenium.type("css=input[name=\"varSearchString\"]", "7123");
  		Thread.sleep(2000);
  		/*selenium.selectWindow("null");*/
  		verifyTrue(selenium.isElementPresent("//input[3]"));
  		selenium.click("//input[3]");
  		Thread.sleep(8000);
  		for (int second = 0;; second++) {
  			if (second >= 60) fail("timeout");
  			try { if (selenium.isElementPresent("id=item")) break; } catch (Exception e) {}
  			Thread.sleep(1000);
  		}

  		Thread.sleep(2000);
  		verifyTrue(selenium.isElementPresent("//div[4]/table/tbody/tr[2]/td/a"));
  		verifyEquals(selenium.getText("css=h3"), "Label Results - Viewing 1 of 1");
  		selenium.click("link=7123");
  		Thread.sleep(69579);
  		for (int second = 0;; second++) {
  			if (second >= 60) fail("timeout");
  			try { if (selenium.isElementPresent("//div/ul/li[9]/a")) break; } catch (Exception e) {}
  			Thread.sleep(1000);
  			System.out.println("OpenRelease End");


  	// 	Edit_Ex_Release
  			System.out.println("Edit_Ex_Release Start");
  			verifyTrue(selenium.isElementPresent("//div/ul/li[9]/a"));
  			selenium.clickAt("//div/ul/li[9]/a", "");
  			Thread.sleep(12579);
  			verifyTrue(selenium.isElementPresent("//div[@id='contentArea']/div[7]/form/table/tbody/tr[2]/td[4]/a"));
  			selenium.clickAt("//div[@id='contentArea']/div[7]/form/table/tbody/tr[2]/td[4]/a", "");
  			Thread.sleep(35000);
  			verifyTrue(selenium.isElementPresent("css=select[name=\"product_type_id\"]"));
  			String ProductType = selenium.getEval("'Movie'");
  			System.out.println("74");
  			verifyTrue(selenium.isElementPresent("css=select[name=\"product_type_id\"]"));
  			selenium.select("css=select[name=\"product_type_id\"]",  ProductType );
  			String ReleaseMetaLanguage = selenium.getEval("'French'");
  			System.out.println("78");
  			verifyTrue(selenium.isElementPresent("css=select[name=\"meta_language\"]"));
  			selenium.select("css=select[name=\"meta_language\"]",  ReleaseMetaLanguage );
  			String ReleaseName = selenium.getEval("'Selenium_Release_'+885686234877");
  			verifyTrue(selenium.isElementPresent("css=input[name=\"release_name_req\"]"));
  			selenium.type("css=input[name=\"release_name_req\"]",  ReleaseName );
  			String LabelImprint = selenium.getEval("'sony records'+(new Date().getDate())");
  			System.out.println("85");
  			verifyTrue(selenium.isElementPresent("css=input[name=\"label\"]"));
  			selenium.type("css=input[name=\"label\"]",  LabelImprint );
  			String ManufacturersUPC = selenium.getEval("''+(new Date().getDate())");
  			verifyTrue(selenium.isElementPresent("css=input[name=\"manufacturer_upc\"]"));
  			selenium.type("css=input[name=\"manufacturer_upc\"]",  ManufacturersUPC );
  			String Line = selenium.getEval("'2012 VAPI'+(new Date().getHours())");
  			verifyTrue(selenium.isElementPresent("css=input[name=\"c_line\"]"));
  			selenium.type("css=input[name=\"c_line\"]",  Line );
  			System.out.println("93");
  			String DescriptionSynopsis = selenium.getEval("'Describe'+(new Date().getTime())");
  			verifyTrue(selenium.isElementPresent("css=textarea[name=\"description\"]"));
  			selenium.type("css=textarea[name=\"description\"]",  DescriptionSynopsis );
  			System.out.println("98");
  			String NotForDistribution = selenium.getEval("'Y'");
  			verifyTrue(selenium.isElementPresent("css=select[name=\"not_for_distribution\"]"));
  			selenium.select("css=select[name=\"not_for_distribution\"]",  NotForDistribution );
  			String TributeByUnknownArtist = selenium.getEval("'Y'");
  			verifyTrue(selenium.isElementPresent("css=select[name=\"unknown_artist\"]"));
  			selenium.select("css=select[name=\"unknown_artist\"]",  TributeByUnknownArtist );
  			String PromoUPC = selenium.getEval("''+(new Date().getDate())");
  			verifyTrue(selenium.isElementPresent("css=input[name=\"promo_upc\"]"));
  			selenium.type("css=input[name=\"promo_upc\"]",  PromoUPC );
  			String Language = selenium.getEval("'English'");
  			verifyTrue(selenium.isElementPresent("css=select[name=\"language_id\"]"));
  			selenium.select("css=select[name=\"language_id\"]",  Language );
  			String SubtitleLanguage = selenium.getEval("'French'");
  			verifyTrue(selenium.isElementPresent("css=select[name=\"subtitle_language_id\"]"));
  			selenium.select("css=select[name=\"subtitle_language_id\"]",  SubtitleLanguage );
  			String InitialPriority = selenium.getEval("'2'");
  			verifyTrue(selenium.isElementPresent("css=select[name=\"priority\"]"));
  			selenium.select("css=select[name=\"priority\"]",  InitialPriority );
  			String NewRelease = selenium.getEval("'Direct To Video'");
  			verifyTrue(selenium.isElementPresent("css=select[name=\"new_release\"]"));
  			selenium.select("css=select[name=\"new_release\"]",  NewRelease );
  			String PreOrderDate = selenium.getEval("'Immediate'");
  			verifyTrue(selenium.isElementPresent("css=select[name=\"prmPreorderType\"]"));
  			selenium.select("css=select[name=\"prmPreorderType\"]",  PreOrderDate );
  			String OrchardArtist = selenium.getEval("'dasda'");
  			verifyTrue(selenium.isElementPresent("css=select[name=\"prmArtistID\"]"));
  			selenium.select("css=select[name=\"prmArtistID\"]",  OrchardArtist );
  			String ReleaseDate = selenium.getEval("'2012-03-31'");
  			verifyTrue(selenium.isElementPresent("css=input[name=\"release_date\"]"));
  			selenium.type("css=input[name=\"release_date\"]",  ReleaseDate );
  			String SaleStartDate = selenium.getEval("'2012-03-19'");
  			verifyTrue(selenium.isElementPresent("css=input[name=\"sale_start_date\"]"));
  			selenium.type("css=input[name=\"sale_start_date\"]",  SaleStartDate );
  			String VODStartDate = selenium.getEval("'2012-05-03'");
  			verifyTrue(selenium.isElementPresent("css=input[name=\"vod_start_date\"]"));
  			selenium.type("css=input[name=\"vod_start_date\"]",  SaleStartDate );
  			String LabelCatalog = selenium.getEval("'2012 synergy'");
  			verifyTrue(selenium.isElementPresent("css=input[name=\"VCN\"]"));
  			selenium.type("css=input[name=\"VCN\"]",  LabelCatalog );
  			String Distribution = selenium.getEval("'phys/digital'");
  			verifyTrue(selenium.isElementPresent("css=select[name=\"distribution\"]"));
  			selenium.select("css=select[name=\"distribution\"]",  Distribution );
  			String PrimaryGenre = selenium.getEval("'Animation'");
  			verifyTrue(selenium.isElementPresent("css=#primary_genre_id"));
  			selenium.select("css=#primary_genre_id",  PrimaryGenre );
  			String ofPromos = selenium.getEval("'adult'");
  			verifyTrue(selenium.isElementPresent("css=input[name=\"promos_number\"]"));
  			selenium.type("css=input[name=\"promos_number\"]",  ofPromos );
  			String PublicDomaininEurope = selenium.getEval("'Y'");
  			verifyTrue(selenium.isElementPresent("css=select[name=\"europe_public_domain\"]"));
  			selenium.select("css=select[name=\"europe_public_domain\"]",  PublicDomaininEurope );
  			String ProductFormat = selenium.getEval("'Boxset'");
  			verifyTrue(selenium.isElementPresent("css=select[name=\"product_format\"]"));
  			selenium.select("css=select[name=\"product_format\"]",  ProductFormat );
  			String Format = selenium.getEval("'DVD'");
  			verifyTrue(selenium.isElementPresent("css=#format"));
  			selenium.select("css=#format",  Format );
  			String Karaoke = selenium.getEval("'Y'");
  			verifyTrue(selenium.isElementPresent("css=select[name=\"karaoke\"]"));
  			selenium.select("css=select[name=\"karaoke\"]",  Karaoke );
  			String DigitalOnly = selenium.getEval("'Y'");
  			verifyTrue(selenium.isElementPresent("css=select[name=\"digital_only\"]"));
  			selenium.select("css=select[name=\"digital_only\"]",  DigitalOnly );
  			String Version = selenium.getEval("'Version'+(new Date().getDate())");
  			verifyTrue(selenium.isElementPresent("css=input[name=\"version\"]"));
  			selenium.type("css=input[name=\"version\"]",  Version );
  			String ShortSynopsis = selenium.getEval("'Version'+(new Date().getDate())");
  			verifyTrue(selenium.isElementPresent("name=short_synopsis_film"));
  			selenium.type("name=short_synopsis_film",  ShortSynopsis );
  			String AMGID = selenium.getEval("'Version'+(new Date().getDate())");
  			verifyTrue(selenium.isElementPresent("css=input[name=\"amd_id_film\"]"));
  			selenium.type("css=input[name=\"amd_id_film\"]",  AMGID );
  			String TheatricalReleaseDate = selenium.getEval("'2012-03-19'");
  			verifyTrue(selenium.isElementPresent("css=input[name=\"theatrical_release_date_film\"]"));
  			selenium.type("css=input[name=\"theatrical_release_date_film\"]",  TheatricalReleaseDate );
  			String PhysicalReleaseDate = selenium.getEval("'2012-03-19'");
  			verifyTrue(selenium.isElementPresent("css=input[name=\"physical_release_date\"]"));
  			selenium.type("css=input[name=\"physical_release_date\"]",  PhysicalReleaseDate );
  			String Subtype = selenium.getEval("'Short'");
  			verifyTrue(selenium.isElementPresent("css=select[name=\"film_subtype_film\"]"));
  			selenium.select("css=select[name=\"film_subtype_film\"]",  Subtype );
  			String CountryofOrigin = selenium.getEval("'Angola'");
  			verifyTrue(selenium.isElementPresent("css=select[name=\"country_of_origin_film\"]"));
  			selenium.select("css=select[name=\"country_of_origin_film\"]",  CountryofOrigin );
  			String Channel = selenium.getEval("'Action'");
  			verifyTrue(selenium.isElementPresent("css=select[name=\"channel_id_film\"]"));
  			selenium.select("css=select[name=\"channel_id_film\"]",  Channel );
  			String ProductionCo = selenium.getEval("'Action'");
  			verifyTrue(selenium.isElementPresent("css=input[name=\"production_co_film\"]"));
  			selenium.type("css=input[name=\"production_co_film\"]",  ProductionCo );
  			String Brand = selenium.getEval("'Action'");
  			verifyTrue(selenium.isElementPresent("css=input[name=\"brand_film\"]"));
  			selenium.type("css=input[name=\"brand_film\"]",  Brand );
  			String TMSMovieID = selenium.getEval("'578'+(new Date().getSeconds())");
  			verifyTrue(selenium.isElementPresent("css=input[name=\"tms_id_film\"]"));
  			selenium.type("css=input[name=\"tms_id_film\"]",  TMSMovieID );
  			String ARMovies = selenium.getEval("'578'+(new Date().getSeconds())");
  			verifyTrue(selenium.isElementPresent("css=input[name=\"reasons_film[ar_movies]\"]"));
  			selenium.type("css=input[name=\"reasons_film[ar_movies]\"]",  ARMovies );
  			String AUOFLC = selenium.getEval("'578'+(new Date().getSeconds())");
  			verifyTrue(selenium.isElementPresent("css=input[name=\"reasons_film[au_oflc]\"]"));
  			selenium.type("css=input[name=\"reasons_film[au_oflc]\"]",  AUOFLC );
  			String FSK = selenium.getEval("'578'+(new Date().getSeconds())");
  			verifyTrue(selenium.isElementPresent("css=input[name=\"reasons_film[fsk]\"]"));
  			selenium.type("css=input[name=\"reasons_film[fsk]\"]",  FSK );
  			String BEMovies = selenium.getEval("'578'+(new Date().getSeconds())");
  			verifyTrue(selenium.isElementPresent("css=input[name=\"reasons_film[be_movies]\"]"));
  			selenium.type("css=input[name=\"reasons_film[be_movies]\"]",  BEMovies );
  			String BOMovies = selenium.getEval("'578'+(new Date().getSeconds())");
  			verifyTrue(selenium.isElementPresent("css=input[name=\"reasons_film[bo_movies]\"]"));
  			selenium.type("css=input[name=\"reasons_film[bo_movies]\"]",  BOMovies );
  			String BRMovies = selenium.getEval("'578'+(new Date().getSeconds())");
  			verifyTrue(selenium.isElementPresent("css=input[name=\"reasons_film[br_movies]\"]"));
  			selenium.type("css=input[name=\"reasons_film[br_movies]\"]",  BRMovies );
  			String BGMovies = selenium.getEval("'578'+(new Date().getSeconds())");
  			verifyTrue(selenium.isElementPresent("css=input[name=\"reasons_film[bg_movies]\"]"));
  			selenium.type("css=input[name=\"reasons_film[bg_movies]\"]",  BGMovies );
  			String CACHVRS = selenium.getEval("'578'+(new Date().getSeconds())");
  			verifyTrue(selenium.isElementPresent("css=input[name=\"reasons_film[ca_chvrs]\"]"));
  			selenium.type("css=input[name=\"reasons_film[ca_chvrs]\"]",  CACHVRS );
  			String CLMovies = selenium.getEval("'578'+(new Date().getSeconds())");
  			verifyTrue(selenium.isElementPresent("css=input[name=\"reasons_film[cl_movies]\"]"));
  			selenium.type("css=input[name=\"reasons_film[cl_movies]\"]",  CLMovies );
  			String COMovies = selenium.getEval("'578'+(new Date().getSeconds())");
  			verifyTrue(selenium.isElementPresent("css=input[name=\"reasons_film[co_movies]\"]"));
  			selenium.type("css=input[name=\"reasons_film[co_movies]\"]",  COMovies );
  			String CRMovies = selenium.getEval("'578'+(new Date().getSeconds())");
  			verifyTrue(selenium.isElementPresent("css=input[name=\"reasons_film[cr_movies]\"]"));
  			selenium.type("css=input[name=\"reasons_film[cr_movies]\"]",  CRMovies );
  			String CYMovies = selenium.getEval("'578'+(new Date().getSeconds())");
  			verifyTrue(selenium.isElementPresent("css=input[name=\"reasons_film[cy_movies]\"]"));
  			selenium.type("css=input[name=\"reasons_film[cy_movies]\"]",  CYMovies );
  			String CZMovies = selenium.getEval("'578'+(new Date().getSeconds())");
  			verifyTrue(selenium.isElementPresent("css=input[name=\"reasons_film[cz_movies]\"]"));
  			selenium.type("css=input[name=\"reasons_film[cz_movies]\"]",  CZMovies );
  			String DKMovies = selenium.getEval("'578'+(new Date().getSeconds())");
  			verifyTrue(selenium.isElementPresent("css=input[name=\"reasons_film[dk_movies]\"]"));
  			selenium.type("css=input[name=\"reasons_film[dk_movies]\"]",  DKMovies );
  			String DOMovies = selenium.getEval("'578'+(new Date().getSeconds())");
  			verifyTrue(selenium.isElementPresent("css=input[name=\"reasons_film[do_movies]\"]"));
  			selenium.type("css=input[name=\"reasons_film[do_movies]\"]",  DOMovies );
  			String ECMovies = selenium.getEval("'578'+(new Date().getSeconds())");
  			verifyTrue(selenium.isElementPresent("css=input[name=\"reasons_film[ec_movies]\"]"));
  			selenium.type("css=input[name=\"reasons_film[ec_movies]\"]",  ECMovies );
  			String SVMovies = selenium.getEval("'578'+(new Date().getSeconds())");
  			verifyTrue(selenium.isElementPresent("css=input[name=\"reasons_film[sv_movies]\"]"));
  			selenium.type("css=input[name=\"reasons_film[sv_movies]\"]",  SVMovies );
  			String EEMovies = selenium.getEval("'578'+(new Date().getSeconds())");
  			verifyTrue(selenium.isElementPresent("css=input[name=\"reasons_film[ee_movies]\"]"));
  			selenium.type("css=input[name=\"reasons_film[ee_movies]\"]",  EEMovies );
  			String FIMovies = selenium.getEval("'578'+(new Date().getSeconds())");
  			verifyTrue(selenium.isElementPresent("css=input[name=\"reasons_film[fi_movies]\"]"));
  			selenium.type("css=input[name=\"reasons_film[fi_movies]\"]",  FIMovies );
  			String FRMovies = selenium.getEval("'578'+(new Date().getSeconds())");
  			verifyTrue(selenium.isElementPresent("css=input[name=\"reasons_film[fr_cnc]\"]"));
  			selenium.type("css=input[name=\"reasons_film[fr_cnc]\"]",  FRMovies );
  			String DEFSK = selenium.getEval("'578'+(new Date().getSeconds())");
  			verifyTrue(selenium.isElementPresent("css=input[name=\"reasons_film[de-fsk]\"]"));
  			selenium.type("css=input[name=\"reasons_film[de-fsk]\"]",  DEFSK );
  			String GRMovies = selenium.getEval("'578'+(new Date().getSeconds())");
  			verifyTrue(selenium.isElementPresent("css=input[name=\"reasons_film[gr_movies]\"]"));
  			selenium.type("css=input[name=\"reasons_film[gr_movies]\"]",  GRMovies );
  			String GTMovies = selenium.getEval("'578'+(new Date().getSeconds())");
  			verifyTrue(selenium.isElementPresent("css=input[name=\"reasons_film[gt_movies]\"]"));
  			selenium.type("css=input[name=\"reasons_film[gt_movies]\"]",  GTMovies );
  			String GYMovies = selenium.getEval("'578'+(new Date().getSeconds())");
  			verifyTrue(selenium.isElementPresent("css=input[name=\"reasons_film[gy_movies]\"]"));
  			selenium.type("css=input[name=\"reasons_film[gy_movies]\"]",  GYMovies );
  			String HNMovies = selenium.getEval("'578'+(new Date().getSeconds())");
  			verifyTrue(selenium.isElementPresent("css=input[name=\"reasons_film[hn_movies]\"]"));
  			selenium.type("css=input[name=\"reasons_film[hn_movies]\"]",  HNMovies );
  			String HUMovies = selenium.getEval("'578'+(new Date().getSeconds())");
  			verifyTrue(selenium.isElementPresent("css=input[name=\"reasons_film[hu_movies]\"]"));
  			selenium.type("css=input[name=\"reasons_film[hu_movies]\"]",  HUMovies );
  			String IEIfco = selenium.getEval("'578'+(new Date().getSeconds())");
  			verifyTrue(selenium.isElementPresent("css=input[name=\"reasons_film[ie_ifco]\"]"));
  			selenium.type("css=input[name=\"reasons_film[ie_ifco]\"]",  IEIfco );
  			String ITMovies = selenium.getEval("'578'+(new Date().getSeconds())");
  			verifyTrue(selenium.isElementPresent("css=input[name=\"reasons_film[it_movies]\"]"));
  			selenium.type("css=input[name=\"reasons_film[it_movies]\"]",  ITMovies );
  			String JMMovies = selenium.getEval("'578'+(new Date().getSeconds())");
  			verifyTrue(selenium.isElementPresent("css=input[name=\"reasons_film[jm_movies]\"]"));
  			selenium.type("css=input[name=\"reasons_film[jm_movies]\"]",  JMMovies );
  			String JPEIRIN = selenium.getEval("'578'+(new Date().getSeconds())");
  			verifyTrue(selenium.isElementPresent("css=input[name=\"reasons_film[jp_eirin]\"]"));
  			selenium.type("css=input[name=\"reasons_film[jp_eirin]\"]",  JPEIRIN );
  			String LVMovies = selenium.getEval("'578'+(new Date().getSeconds())");
  			verifyTrue(selenium.isElementPresent("css=input[name=\"reasons_film[lv_movies]\"]"));
  			selenium.type("css=input[name=\"reasons_film[lv_movies]\"]",  LVMovies );
  			String LTMovies = selenium.getEval("'578'+(new Date().getSeconds())");
  			verifyTrue(selenium.isElementPresent("css=input[name=\"reasons_film[lt_movies]\"]"));
  			selenium.type("css=input[name=\"reasons_film[lt_movies]\"]",  LTMovies );
  			String LUMovies = selenium.getEval("'578'+(new Date().getSeconds())");
  			verifyTrue(selenium.isElementPresent("css=input[name=\"reasons_film[lu_movies]\"]"));
  			selenium.type("css=input[name=\"reasons_film[lu_movies]\"]",  LUMovies );
  			String MTMovies = selenium.getEval("'578'+(new Date().getSeconds())");
  			verifyTrue(selenium.isElementPresent("css=input[name=\"reasons_film[mt_movies]\"]"));
  			selenium.type("css=input[name=\"reasons_film[mt_movies]\"]",  MTMovies );
  			String MXMovies = selenium.getEval("'578'+(new Date().getSeconds())");
  			verifyTrue(selenium.isElementPresent("css=input[name=\"reasons_film[mx_movies]\"]"));
  			selenium.type("css=input[name=\"reasons_film[mx_movies]\"]",  MXMovies );
  			String NLMovies = selenium.getEval("'578'+(new Date().getSeconds())");
  			verifyTrue(selenium.isElementPresent("css=input[name=\"reasons_film[nl_movies]\"]"));
  			selenium.type("css=input[name=\"reasons_film[nl_movies]\"]",  NLMovies );
  			String NZOflc = selenium.getEval("'578'+(new Date().getSeconds())");
  			verifyTrue(selenium.isElementPresent("css=input[name=\"reasons_film[nz_oflc]\"]"));
  			selenium.type("css=input[name=\"reasons_film[nz_oflc]\"]",  NZOflc );
  			String NIMovies = selenium.getEval("'578'+(new Date().getSeconds())");
  			verifyTrue(selenium.isElementPresent("css=input[name=\"reasons_film[ni_movies]\"]"));
  			selenium.type("css=input[name=\"reasons_film[ni_movies]\"]",  NIMovies );
  			String NOMovies = selenium.getEval("'578'+(new Date().getSeconds())");
  			verifyTrue(selenium.isElementPresent("css=input[name=\"reasons_film[no_movies]\"]"));
  			selenium.type("css=input[name=\"reasons_film[no_movies]\"]",  NOMovies );
  			String PAMovies = selenium.getEval("'578'+(new Date().getSeconds())");
  			verifyTrue(selenium.isElementPresent("css=input[name=\"reasons_film[pa_movies]\"]"));
  			selenium.type("css=input[name=\"reasons_film[pa_movies]\"]",  PAMovies );
  			String PYMovies = selenium.getEval("'578'+(new Date().getSeconds())");
  			verifyTrue(selenium.isElementPresent("css=input[name=\"reasons_film[py_movies]\"]"));
  			selenium.type("css=input[name=\"reasons_film[py_movies]\"]",  PYMovies );
  			String PEMovies = selenium.getEval("'578'+(new Date().getSeconds())");
  			verifyTrue(selenium.isElementPresent("css=input[name=\"reasons_film[pe_movies]\"]"));
  			selenium.type("css=input[name=\"reasons_film[pe_movies]\"]",  PEMovies );
  			String PLMovies = selenium.getEval("'578'+(new Date().getSeconds())");
  			verifyTrue(selenium.isElementPresent("css=input[name=\"reasons_film[pl_movies]\"]"));
  			selenium.type("css=input[name=\"reasons_film[pl_movies]\"]",  PLMovies );
  			String PTMovies = selenium.getEval("'578'+(new Date().getSeconds())");
  			verifyTrue(selenium.isElementPresent("css=input[name=\"reasons_film[pt_movies]\"]"));
  			selenium.type("css=input[name=\"reasons_film[pt_movies]\"]",  PTMovies );
  			String CARcq = selenium.getEval("'578'+(new Date().getSeconds())");
  			verifyTrue(selenium.isElementPresent("css=input[name=\"reasons_film[ca-rcq]\"]"));
  			selenium.type("css=input[name=\"reasons_film[ca-rcq]\"]",  CARcq );
  			String ROMovies = selenium.getEval("'578'+(new Date().getSeconds())");
  			verifyTrue(selenium.isElementPresent("css=input[name=\"reasons_film[ro_movies]\"]"));
  			selenium.type("css=input[name=\"reasons_film[ro_movies]\"]",  ROMovies );
  			selenium.selectWindow("null");
  			String SKMovies = selenium.getEval("'578'+(new Date().getSeconds())");
  			verifyTrue(selenium.isElementPresent("css=input[name=\"reasons_film[sk_movies]\"]"));
  			selenium.type("css=input[name=\"reasons_film[sk_movies]\"]",  SKMovies );
  			String SIMovies = selenium.getEval("'578'+(new Date().getSeconds())");
  			verifyTrue(selenium.isElementPresent("css=input[name=\"reasons_film[si_movies]\"]"));
  			selenium.type("css=input[name=\"reasons_film[si_movies]\"]",  SIMovies );
  			String ESMovies = selenium.getEval("'578'+(new Date().getSeconds())");
  			verifyTrue(selenium.isElementPresent("css=input[name=\"reasons_film[es_movies]\"]"));
  			selenium.type("css=input[name=\"reasons_film[es_movies]\"]",  ESMovies );
  			String SRMovies = selenium.getEval("'578'+(new Date().getSeconds())");
  			verifyTrue(selenium.isElementPresent("css=input[name=\"reasons_film[sr_movies]\"]"));
  			selenium.type("css=input[name=\"reasons_film[sr_movies]\"]",  SRMovies );
  			String CHMovies = selenium.getEval("'578'+(new Date().getSeconds())");
  			verifyTrue(selenium.isElementPresent("css=input[name=\"reasons_film[ch_movies]\"]"));
  			selenium.type("css=input[name=\"reasons_film[ch_movies]\"]",  CHMovies );
  			String SEMovies = selenium.getEval("'578'+(new Date().getSeconds())");
  			verifyTrue(selenium.isElementPresent("css=input[name=\"reasons_film[se_movies]\"]"));
  			selenium.type("css=input[name=\"reasons_film[se_movies]\"]",  SEMovies );
  			String BBFC = selenium.getEval("'578'+(new Date().getSeconds())");
  			verifyTrue(selenium.isElementPresent("css=input[name=\"reasons_film[bbfc]\"]"));
  			selenium.type("css=input[name=\"reasons_film[bbfc]\"]",  BBFC );
  			String UYMovies = selenium.getEval("'578'+(new Date().getSeconds())");
  			verifyTrue(selenium.isElementPresent("css=input[name=\"reasons_film[uy_movies]\"]"));
  			selenium.type("css=input[name=\"reasons_film[uy_movies]\"]",  UYMovies );
  			String MPAA = selenium.getEval("'578'+(new Date().getSeconds())");
  			verifyTrue(selenium.isElementPresent("css=input[name=\"reasons_film[mpaa]\"]"));
  			selenium.type("css=input[name=\"reasons_film[mpaa]\"]",  MPAA );
  			String VEMovies = selenium.getEval("'578'+(new Date().getSeconds())");
  			verifyTrue(selenium.isElementPresent("css=input[name=\"reasons_film[ve_movies]\"]"));
  			selenium.type("css=input[name=\"reasons_film[ve_movies]\"]",  VEMovies );
  			String ArgentinaARMovies = selenium.getEval("'ATP'");
  			verifyTrue(selenium.isElementPresent("//div[17]/div/table/tbody/tr/td/select"));
  			selenium.select("//div[17]/div/table/tbody/tr/td/select",  ArgentinaARMovies );
  			String AustraliaAUOFLC = selenium.getEval("'G'");
  			verifyTrue(selenium.isElementPresent("//div[17]/div/table/tbody/tr[2]/td/select"));
  			selenium.select("//div[17]/div/table/tbody/tr[2]/td/select",  AustraliaAUOFLC );
  			String AustriaFSK = selenium.getEval("'ab 0 Jahren'");
  			verifyTrue(selenium.isElementPresent("//div[17]/div/table/tbody/tr[3]/td/select"));
  			selenium.select("//div[17]/div/table/tbody/tr[3]/td/select",  AustriaFSK );
  			String BelgiumBEMovies = selenium.getEval("'12'");
  			verifyTrue(selenium.isElementPresent("//div[17]/div/table/tbody/tr[4]/td/select"));
  			selenium.select("//div[17]/div/table/tbody/tr[4]/td/select",  BelgiumBEMovies );
  			String BoliviaBOMovies = selenium.getEval("'14'");
  			verifyTrue(selenium.isElementPresent("//div[17]/div/table/tbody/tr[5]/td/select"));
  			selenium.select("//div[17]/div/table/tbody/tr[5]/td/select",  BoliviaBOMovies );
  			String BrazilBRMovies = selenium.getEval("'10'");
  			verifyTrue(selenium.isElementPresent("//div[17]/div/table/tbody/tr[6]/td/select"));
  			selenium.select("//div[17]/div/table/tbody/tr[6]/td/select",  BrazilBRMovies );
  			String BulgariaBGMovies = selenium.getEval("'A'");
  			verifyTrue(selenium.isElementPresent("//div[17]/div/table/tbody/tr[7]/td/select"));
  			selenium.select("//div[17]/div/table/tbody/tr[7]/td/select",  BulgariaBGMovies );
  			String CanadaCACHVRS = selenium.getEval("'14A'");
  			verifyTrue(selenium.isElementPresent("//div[17]/div/table/tbody/tr[8]/td/select"));
  			selenium.select("//div[17]/div/table/tbody/tr[8]/td/select",  CanadaCACHVRS );
  			String ChileCLMovies = selenium.getEval("'14'");
  			verifyTrue(selenium.isElementPresent("//div[17]/div/table/tbody/tr[9]/td/select"));
  			selenium.select("//div[17]/div/table/tbody/tr[9]/td/select",  ChileCLMovies );
  			String ColombiaCOMovies = selenium.getEval("'12'");
  			verifyTrue(selenium.isElementPresent("//div[17]/div/table/tbody/tr[10]/td/select"));
  			selenium.select("//div[17]/div/table/tbody/tr[10]/td/select",  ColombiaCOMovies );
  			String CostaRicaCRMovies = selenium.getEval("'12'");
  			verifyTrue(selenium.isElementPresent("//div[17]/div/table/tbody/tr[11]/td/select"));
  			selenium.select("//div[17]/div/table/tbody/tr[11]/td/select",  CostaRicaCRMovies );
  			String CostaRicaCRMoviesnew = selenium.getEval("'12'");
  			verifyTrue(selenium.isElementPresent("//div[17]/div/table/tbody/tr[11]/td/select"));
  			selenium.select("//div[17]/div/table/tbody/tr[11]/td/select",  CostaRicaCRMoviesnew );
  			String CyprusCYMovies = selenium.getEval("'12'");
  			verifyTrue(selenium.isElementPresent("//div[17]/div/table/tbody/tr[12]/td/select"));
  			selenium.select("//div[17]/div/table/tbody/tr[12]/td/select",  CyprusCYMovies );
  			String CzechRepublicCZMovies = selenium.getEval("'12+'");
  			verifyTrue(selenium.isElementPresent("//div[17]/div/table/tbody/tr[13]/td/select"));
  			selenium.select("//div[17]/div/table/tbody/tr[13]/td/select",  CzechRepublicCZMovies );
  			String DenmarkDKMovies = selenium.getEval("'11'");
  			verifyTrue(selenium.isElementPresent("//div[17]/div/table/tbody/tr[14]/td/select"));
  			selenium.select("//div[17]/div/table/tbody/tr[14]/td/select",  DenmarkDKMovies );
  			String DominicanRepublicDOMovies = selenium.getEval("'Todos'");
  			verifyTrue(selenium.isElementPresent("//div[17]/div/table/tbody/tr[15]/td/select"));
  			selenium.select("//div[17]/div/table/tbody/tr[15]/td/select",  DominicanRepublicDOMovies );
  			String EcuadorECMovies = selenium.getEval("'12'");
  			verifyTrue(selenium.isElementPresent("//div[17]/div/table/tbody/tr[16]/td/select"));
  			selenium.select("//div[17]/div/table/tbody/tr[16]/td/select",  EcuadorECMovies );
  			String EISalvadorSVMovies = selenium.getEval("'12'");
  			verifyTrue(selenium.isElementPresent("//div[17]/div/table/tbody/tr[17]/td/select"));
  			selenium.select("//div[17]/div/table/tbody/tr[17]/td/select",  EISalvadorSVMovies );
  			String EstoniaEEMovies = selenium.getEval("'K12'");
  			verifyTrue(selenium.isElementPresent("//div[17]/div/table/tbody/tr[18]/td/select"));
  			selenium.select("//div[17]/div/table/tbody/tr[18]/td/select",  EstoniaEEMovies );
  			String FinlandFIovies = selenium.getEval("'K-11'");
  			verifyTrue(selenium.isElementPresent("//div[17]/div/table/tbody/tr[19]/td/select"));
  			selenium.select("//div[17]/div/table/tbody/tr[19]/td/select",  FinlandFIovies );
  			String FranceFRCNC = selenium.getEval("'-10'");
  			verifyTrue(selenium.isElementPresent("//div[17]/div/table/tbody/tr[20]/td/select"));
  			selenium.select("//div[17]/div/table/tbody/tr[20]/td/select",  FranceFRCNC );
  			String GermanyDEFSK = selenium.getEval("'ab 12 Jahren'");
  			verifyTrue(selenium.isElementPresent("//div[17]/div/table/tbody/tr[21]/td/select"));
  			selenium.select("//div[17]/div/table/tbody/tr[21]/td/select",  GermanyDEFSK );
  			String GreeceGRMovies = selenium.getEval("'K'");
  			verifyTrue(selenium.isElementPresent("//div[17]/div/table/tbody/tr[22]/td/select"));
  			selenium.select("//div[17]/div/table/tbody/tr[22]/td/select",  GreeceGRMovies );
  			String GuatemalaGTMovies = selenium.getEval("'A'");
  			verifyTrue(selenium.isElementPresent("//div[17]/div/table/tbody/tr[23]/td/select"));
  			selenium.select("//div[17]/div/table/tbody/tr[23]/td/select",  GuatemalaGTMovies );
  			String GuyanaGYMovies = selenium.getEval("'All Ages'");
  			verifyTrue(selenium.isElementPresent("//div[17]/div/table/tbody/tr[24]/td/select"));
  			selenium.select("//div[17]/div/table/tbody/tr[24]/td/select",  GuyanaGYMovies );
  			String GuyanaGYMovies02 = selenium.getEval("'All Ages'");
  			verifyTrue(selenium.isElementPresent("//div[17]/div/table/tbody/tr[24]/td/select"));
  			selenium.select("//div[17]/div/table/tbody/tr[24]/td/select",  GuyanaGYMovies02 );
  			String HungaryHUMovies = selenium.getEval("'12'");
  			verifyTrue(selenium.isElementPresent("//div[17]/div/table/tbody/tr[26]/td/select"));
  			selenium.select("//div[17]/div/table/tbody/tr[26]/td/select",  HungaryHUMovies );
  			String IrelandIEIFCO = selenium.getEval("'12'");
  			verifyTrue(selenium.isElementPresent("//div[17]/div/table/tbody/tr[27]/td/select"));
  			selenium.select("//div[17]/div/table/tbody/tr[27]/td/select",  IrelandIEIFCO );
  			String ItalyITMovies = selenium.getEval("'T'");
  			verifyTrue(selenium.isElementPresent("//div[17]/div/table/tbody/tr[28]/td/select"));
  			selenium.select("//div[17]/div/table/tbody/tr[28]/td/select",  ItalyITMovies );
  			String JamaicaJMMovies = selenium.getEval("'U'");
  			verifyTrue(selenium.isElementPresent("//div[17]/div/table[2]/tbody/tr/td/select"));
  			selenium.select("//div[17]/div/table[2]/tbody/tr/td/select",  JamaicaJMMovies );
  			String JapanJPEIRIN = selenium.getEval("'G'");
  			verifyTrue(selenium.isElementPresent("//div[17]/div/table[2]/tbody/tr[2]/td/select"));
  			selenium.select("//div[17]/div/table[2]/tbody/tr[2]/td/select",  JapanJPEIRIN );
  			String LatviaLVMovies = selenium.getEval("'16+'");
  			verifyTrue(selenium.isElementPresent("//div[17]/div/table[2]/tbody/tr[3]/td/select"));
  			selenium.select("//div[17]/div/table[2]/tbody/tr[3]/td/select",  LatviaLVMovies );
  			String LithuaniaLTMovies = selenium.getEval("'A'");
  			verifyTrue(selenium.isElementPresent("//div[17]/div/table[2]/tbody/tr[4]/td/select"));
  			selenium.select("//div[17]/div/table[2]/tbody/tr[4]/td/select",  LithuaniaLTMovies );
  			String LuxembourgLUMovies = selenium.getEval("'12'");
  			verifyTrue(selenium.isElementPresent("//div[17]/div/table[2]/tbody/tr[5]/td/select"));
  			selenium.select("//div[17]/div/table[2]/tbody/tr[5]/td/select",  LuxembourgLUMovies );
  			String MaltaMTMovies = selenium.getEval("'12'");
  			verifyTrue(selenium.isElementPresent("//div[17]/div/table[2]/tbody/tr[6]/td/select"));
  			selenium.select("//div[17]/div/table[2]/tbody/tr[6]/td/select",  MaltaMTMovies );
  			String MexicoMXMovies = selenium.getEval("'A'");
  			verifyTrue(selenium.isElementPresent("//div[17]/div/table[2]/tbody/tr[7]/td/select"));
  			selenium.select("//div[17]/div/table[2]/tbody/tr[7]/td/select",  MexicoMXMovies );
  			String NetherlandsNLMovies = selenium.getEval("'12'");
  			verifyTrue(selenium.isElementPresent("//div[17]/div/table[2]/tbody/tr[8]/td/select"));
  			selenium.select("//div[17]/div/table[2]/tbody/tr[8]/td/select",  NetherlandsNLMovies );
  			String NewZealandNZOFLC = selenium.getEval("'G'");
  			verifyTrue(selenium.isElementPresent("//div[17]/div/table[2]/tbody/tr[9]/td/select"));
  			selenium.select("//div[17]/div/table[2]/tbody/tr[9]/td/select",  NewZealandNZOFLC );
  			String NicaraguaNIMovies = selenium.getEval("'G'");
  			verifyTrue(selenium.isElementPresent("//div[17]/div/table[2]/tbody/tr[9]/td/select"));
  			selenium.select("//div[17]/div/table[2]/tbody/tr[9]/td/select",  NicaraguaNIMovies );
  			String NorwayNOMovies = selenium.getEval("'PG'");
  			verifyTrue(selenium.isElementPresent("//div[17]/div/table[2]/tbody/tr[10]/td/select"));
  			selenium.select("//div[17]/div/table[2]/tbody/tr[10]/td/select",  NorwayNOMovies );
  			String PanamaPAMovies = selenium.getEval("'11'");
  			verifyTrue(selenium.isElementPresent("//div[17]/div/table[2]/tbody/tr[11]/td/select"));
  			selenium.select("//div[17]/div/table[2]/tbody/tr[11]/td/select",  PanamaPAMovies );
  			String ParaguayPYMovies = selenium.getEval("'A'");
  			verifyTrue(selenium.isElementPresent("//div[17]/div/table[2]/tbody/tr[12]/td/select"));
  			selenium.select("//div[17]/div/table[2]/tbody/tr[12]/td/select",  ParaguayPYMovies );
  			String PeruPEMovies = selenium.getEval("'13'");
  			verifyTrue(selenium.isElementPresent("//div[17]/div/table[2]/tbody/tr[13]/td/select"));
  			selenium.select("//div[17]/div/table[2]/tbody/tr[13]/td/select",  PeruPEMovies );
  			String PolandPlMovies = selenium.getEval("'14'");
  			verifyTrue(selenium.isElementPresent("//div[17]/div/table[2]/tbody/tr[14]/td/select"));
  			selenium.select("//div[17]/div/table[2]/tbody/tr[14]/td/select",  PolandPlMovies );
  			String PortugalPTMovies = selenium.getEval("'12'");
  			verifyTrue(selenium.isElementPresent("//div[17]/div/table[2]/tbody/tr[15]/td/select"));
  			selenium.select("//div[17]/div/table[2]/tbody/tr[15]/td/select",  PortugalPTMovies );
  			String QuebecCARCQ = selenium.getEval("'M/12'");
  			verifyTrue(selenium.isElementPresent("//div[17]/div/table[2]/tbody/tr[16]/td/select"));
  			selenium.select("//div[17]/div/table[2]/tbody/tr[16]/td/select",  QuebecCARCQ );
  			String QuebecCARCQ02 = selenium.getEval("'13+'");
  			verifyTrue(selenium.isElementPresent("//div[17]/div/table[2]/tbody/tr[17]/td/select"));
  			selenium.select("//div[17]/div/table[2]/tbody/tr[17]/td/select",  QuebecCARCQ02 );
  			String RomaniaROMovies = selenium.getEval("'A.G.'");
  			verifyTrue(selenium.isElementPresent("//div[17]/div/table[2]/tbody/tr[18]/td/select"));
  			selenium.select("//div[17]/div/table[2]/tbody/tr[18]/td/select",  RomaniaROMovies );
  			String SlovakiaSKMovies = selenium.getEval("'12'");
  			verifyTrue(selenium.isElementPresent("//div[17]/div/table[2]/tbody/tr[19]/td/select"));
  			selenium.select("//div[17]/div/table[2]/tbody/tr[19]/td/select",  SlovakiaSKMovies );
  			String SloveniaSIMovies = selenium.getEval("'+15'");
  			verifyTrue(selenium.isElementPresent("//div[17]/div/table[2]/tbody/tr[20]/td/select"));
  			selenium.select("//div[17]/div/table[2]/tbody/tr[20]/td/select",  SloveniaSIMovies );
  			String SpainESMovies = selenium.getEval("'12'");
  			verifyTrue(selenium.isElementPresent("//div[17]/div/table[2]/tbody/tr[21]/td/select"));
  			selenium.select("//div[17]/div/table[2]/tbody/tr[21]/td/select",  SpainESMovies );
  			String SurinameSRMovies = selenium.getEval("'All Ages'");
  			verifyTrue(selenium.isElementPresent("//div[17]/div/table[2]/tbody/tr[22]/td/select"));
  			selenium.select("//div[17]/div/table[2]/tbody/tr[22]/td/select",  SurinameSRMovies );
  			String SwedenSEMovies = selenium.getEval("'Från 15 år'");
  			verifyTrue(selenium.isElementPresent("//div[17]/div/table[2]/tbody/tr[23]/td/select"));
  			selenium.select("//div[17]/div/table[2]/tbody/tr[23]/td/select",  SwedenSEMovies );
  			String SwitzerlandCHMovies = selenium.getEval("'0'");
  			verifyTrue(selenium.isElementPresent("//div[17]/div/table[2]/tbody/tr[24]/td/select"));
  			selenium.select("//div[17]/div/table[2]/tbody/tr[24]/td/select",  SwitzerlandCHMovies );
  			String UnitedKingdomBBFC = selenium.getEval("'12'");
  			verifyTrue(selenium.isElementPresent("//div[17]/div/table[2]/tbody/tr[25]/td/select"));
  			selenium.select("//div[17]/div/table[2]/tbody/tr[25]/td/select",  UnitedKingdomBBFC );
  			String UruguayUYMovies = selenium.getEval("'+12'");
  			verifyTrue(selenium.isElementPresent("//div[17]/div/table[2]/tbody/tr[26]/td/select"));
  			selenium.select("//div[17]/div/table[2]/tbody/tr[26]/td/select",  UruguayUYMovies );
  			String USMPAA = selenium.getEval("'G'");
  			verifyTrue(selenium.isElementPresent("//div[17]/div/table[2]/tbody/tr[27]/td/select"));
  			selenium.select("//div[17]/div/table[2]/tbody/tr[27]/td/select",  USMPAA );
  			String VenezuelaVEMovies = selenium.getEval("'A'");
  			verifyTrue(selenium.isElementPresent("//div[17]/div/table[2]/tbody/tr[28]/td/select"));
  			selenium.select("//div[17]/div/table[2]/tbody/tr[28]/td/select",  VenezuelaVEMovies );
  			System.out.println("Edit_Ex_Release End");

  			System.out.println("Edit_Ex_Release Verification_Start");			
  			verifyEquals(selenium.getValue("css=select[name=\"product_type_id\"]"), "3");
  			verifyEquals(selenium.getValue("css=select[name=\"meta_language\"]"), "FRE");
  			verifyEquals(selenium.getValue("css=input[name=\"release_name_req\"]"),  ReleaseName );
  			verifyEquals(selenium.getValue("css=input[name=\"label\"]"),  LabelImprint );
  			verifyEquals(selenium.getValue("css=input[name=\"manufacturer_upc\"]"),  ManufacturersUPC );
  			verifyEquals(selenium.getValue("css=input[name=\"c_line\"]"),  Line );
  			verifyEquals(selenium.getValue("css=textarea[name=\"description\"]"),  DescriptionSynopsis );
  			verifyEquals(selenium.getValue("css=select[name=\"not_for_distribution\"]"),  NotForDistribution );
  			verifyEquals(selenium.getValue("css=select[name=\"unknown_artist\"]"),  TributeByUnknownArtist );
  			verifyEquals(selenium.getValue("css=input[name=\"promo_upc\"]"),  PromoUPC );
  			verifyEquals(selenium.getValue("css=select[name=\"language_id\"]"),  Language );
  			verifyEquals(selenium.getValue("css=select[name=\"subtitle_language_id\"]"), "FRE");
  			verifyEquals(selenium.getValue("css=select[name=\"priority\"]"),  InitialPriority );
  			verifyEquals(selenium.getValue("css=select[name=\"new_release\"]"), "Direct_To_Video");
  			verifyEquals(selenium.getValue("css=select[name=\"prmPreorderType\"]"),  PreOrderDate );
  			verifyEquals(selenium.getValue("css=select[name=\"prmArtistID\"]"), "167218");
  			verifyEquals(selenium.getValue("css=input[name=\"release_date\"]"),  ReleaseDate );
  			verifyEquals(selenium.getValue("css=input[name=\"sale_start_date\"]"),  SaleStartDate );
  			verifyEquals(selenium.getValue("css=input[name=\"vod_start_date\"]"),  SaleStartDate );
  			verifyEquals(selenium.getValue("css=input[name=\"VCN\"]"),  LabelCatalog );
  			verifyEquals(selenium.getValue("css=select[name=\"distribution\"]"),  Distribution );
  			verifyEquals(selenium.getValue("css=#primary_genre_id"), "3");
  			verifyEquals(selenium.getValue("css=input[name=\"promos_number\"]"),  ofPromos );
  			verifyEquals(selenium.getValue("css=select[name=\"europe_public_domain\"]"),  PublicDomaininEurope );
  			verifyEquals(selenium.getValue("css=select[name=\"product_format\"]"),  ProductFormat );
  			verifyEquals(selenium.getValue("css=#format"),  Format );
  			verifyEquals(selenium.getValue("css=select[name=\"karaoke\"]"),  Karaoke );
  			verifyEquals(selenium.getValue("css=select[name=\"digital_only\"]"),  DigitalOnly );
  			verifyEquals(selenium.getValue("css=input[name=\"version\"]"),  Version );
  			verifyEquals(selenium.getValue("name=short_synopsis_film"),  ShortSynopsis );
  			verifyEquals(selenium.getValue("css=input[name=\"amd_id_film\"]"),  AMGID );
  			verifyEquals(selenium.getValue("css=input[name=\"theatrical_release_date_film\"]"),  TheatricalReleaseDate );
  			verifyEquals(selenium.getValue("css=input[name=\"physical_release_date\"]"),  PhysicalReleaseDate );
  			verifyEquals(selenium.getValue("css=select[name=\"film_subtype_film\"]"), "2");
  			verifyEquals(selenium.getValue("css=select[name=\"country_of_origin_film\"]"), "21");
  			verifyEquals(selenium.getValue("css=select[name=\"channel_id_film\"]"), "20");
  			verifyEquals(selenium.getValue("css=input[name=\"production_co_film\"]"),  ProductionCo );
  			verifyEquals(selenium.getValue("css=input[name=\"brand_film\"]"),  Brand );
  			verifyEquals(selenium.getValue("css=input[name=\"tms_id_film\"]"),  TMSMovieID );
  			verifyEquals(selenium.getValue("css=input[name=\"reasons_film[ar_movies]\"]"),  ARMovies );
  			verifyEquals(selenium.getValue("css=input[name=\"reasons_film[au_oflc]\"]"),  AUOFLC );
  			verifyEquals(selenium.getValue("css=input[name=\"reasons_film[fsk]\"]"),  FSK );
  			verifyEquals(selenium.getValue("css=input[name=\"reasons_film[be_movies]\"]"),  BEMovies );
  			verifyEquals(selenium.getValue("css=input[name=\"reasons_film[bo_movies]\"]"),  BOMovies );
  			verifyEquals(selenium.getValue("css=input[name=\"reasons_film[br_movies]\"]"),  BRMovies );
  			verifyEquals(selenium.getValue("css=input[name=\"reasons_film[bg_movies]\"]"),  BGMovies );
  			verifyEquals(selenium.getValue("css=input[name=\"reasons_film[ca_chvrs]\"]"),  CACHVRS );
  			verifyEquals(selenium.getValue("css=input[name=\"reasons_film[cl_movies]\"]"),  CLMovies );
  			verifyEquals(selenium.getValue("css=input[name=\"reasons_film[co_movies]\"]"),  COMovies );
  			verifyEquals(selenium.getValue("css=input[name=\"reasons_film[cr_movies]\"]"),  CRMovies );
  			verifyEquals(selenium.getValue("css=input[name=\"reasons_film[cy_movies]\"]"),  CYMovies );
  			verifyEquals(selenium.getValue("css=input[name=\"reasons_film[cz_movies]\"]"),  CZMovies );
  			verifyEquals(selenium.getValue("css=input[name=\"reasons_film[dk_movies]\"]"),  DKMovies );
  			verifyEquals(selenium.getValue("css=input[name=\"reasons_film[do_movies]\"]"),  DOMovies );
  			verifyEquals(selenium.getValue("css=input[name=\"reasons_film[ec_movies]\"]"),  ECMovies );
  			verifyEquals(selenium.getValue("css=input[name=\"reasons_film[sv_movies]\"]"),  SVMovies );
  			verifyEquals(selenium.getValue("css=input[name=\"reasons_film[ee_movies]\"]"),  EEMovies );
  			verifyEquals(selenium.getValue("css=input[name=\"reasons_film[fi_movies]\"]"),  FIMovies );
  			verifyEquals(selenium.getValue("css=input[name=\"reasons_film[fr_cnc]\"]"),  FRMovies );
  			verifyEquals(selenium.getValue("css=input[name=\"reasons_film[de-fsk]\"]"),  DEFSK );
  			verifyEquals(selenium.getValue("css=input[name=\"reasons_film[gr_movies]\"]"),  GRMovies );
  			verifyEquals(selenium.getValue("css=input[name=\"reasons_film[gt_movies]\"]"),  GTMovies );
  			verifyEquals(selenium.getValue("css=input[name=\"reasons_film[gy_movies]\"]"),  GYMovies );
  			verifyEquals(selenium.getValue("css=input[name=\"reasons_film[hn_movies]\"]"),  HNMovies );
  			verifyEquals(selenium.getValue("css=input[name=\"reasons_film[hu_movies]\"]"),  HUMovies );
  			verifyEquals(selenium.getValue("css=input[name=\"reasons_film[ie_ifco]\"]"),  IEIfco );
  			verifyEquals(selenium.getValue("css=input[name=\"reasons_film[it_movies]\"]"),  ITMovies );
  			verifyEquals(selenium.getValue("css=input[name=\"reasons_film[jm_movies]\"]"),  JMMovies );
  			verifyEquals(selenium.getValue("css=input[name=\"reasons_film[jp_eirin]\"]"),  JPEIRIN );
  			verifyEquals(selenium.getValue("css=input[name=\"reasons_film[lv_movies]\"]"),  LVMovies );
  			verifyEquals(selenium.getValue("css=input[name=\"reasons_film[lt_movies]\"]"),  LTMovies );
  			verifyEquals(selenium.getValue("css=input[name=\"reasons_film[lu_movies]\"]"),  LUMovies );
  			verifyEquals(selenium.getValue("css=input[name=\"reasons_film[mt_movies]\"]"),  MTMovies );
  			verifyEquals(selenium.getValue("css=input[name=\"reasons_film[mx_movies]\"]"),  MXMovies );
  			verifyEquals(selenium.getValue("css=input[name=\"reasons_film[nl_movies]\"]"),  NLMovies );
  			verifyEquals(selenium.getValue("css=input[name=\"reasons_film[nz_oflc]\"]"),  NZOflc );
  			verifyEquals(selenium.getValue("css=input[name=\"reasons_film[ni_movies]\"]"),  NIMovies );
  			verifyEquals(selenium.getValue("css=input[name=\"reasons_film[no_movies]\"]"),  NOMovies );
  			verifyEquals(selenium.getValue("css=input[name=\"reasons_film[pa_movies]\"]"),  PAMovies );
  			verifyEquals(selenium.getValue("css=input[name=\"reasons_film[py_movies]\"]"),  PYMovies );
  			verifyEquals(selenium.getValue("css=input[name=\"reasons_film[pe_movies]\"]"),  PEMovies );
  			verifyEquals(selenium.getValue("css=input[name=\"reasons_film[pl_movies]\"]"),  PLMovies );
  			verifyEquals(selenium.getValue("css=input[name=\"reasons_film[pt_movies]\"]"),  PTMovies );
  			verifyEquals(selenium.getValue("css=input[name=\"reasons_film[ca-rcq]\"]"),  CARcq );
  			verifyEquals(selenium.getValue("css=input[name=\"reasons_film[ro_movies]\"]"),  ROMovies );
  			verifyEquals(selenium.getValue("css=input[name=\"reasons_film[sk_movies]\"]"),  SKMovies );
  			verifyEquals(selenium.getValue("css=input[name=\"reasons_film[si_movies]\"]"),  SIMovies );
  			verifyEquals(selenium.getValue("css=input[name=\"reasons_film[es_movies]\"]"),  ESMovies );
  			verifyEquals(selenium.getValue("css=input[name=\"reasons_film[sr_movies]\"]"),  SRMovies );
  			verifyEquals(selenium.getValue("css=input[name=\"reasons_film[ch_movies]\"]"),  CHMovies );
  			verifyEquals(selenium.getValue("css=input[name=\"reasons_film[se_movies]\"]"),  SEMovies );
  			verifyEquals(selenium.getValue("css=input[name=\"reasons_film[bbfc]\"]"),  BBFC );
  			verifyEquals(selenium.getValue("css=input[name=\"reasons_film[uy_movies]\"]"),  UYMovies );
  			verifyEquals(selenium.getValue("css=input[name=\"reasons_film[mpaa]\"]"),  MPAA );
  			verifyEquals(selenium.getValue("css=input[name=\"reasons_film[ve_movies]\"]"),  VEMovies );
  			verifyEquals(selenium.getValue("//div[17]/div/table/tbody/tr/td/select"), "111");
  			verifyEquals(selenium.getValue("//div[17]/div/table/tbody/tr[2]/td/select"), "74");
  			verifyEquals(selenium.getValue("//div[17]/div/table/tbody/tr[3]/td/select"), "121");
  			verifyEquals(selenium.getValue("//div[17]/div/table/tbody/tr[4]/td/select"), "130");
  			verifyEquals(selenium.getValue("//div[17]/div/table/tbody/tr[5]/td/select"), "146");
  			verifyEquals(selenium.getValue("//div[17]/div/table/tbody/tr[6]/td/select"), "150");
  			verifyEquals(selenium.getValue("//div[17]/div/table/tbody/tr[7]/td/select"), "155");
  			verifyEquals(selenium.getValue("//div[17]/div/table/tbody/tr[8]/td/select"), "82");
  			verifyEquals(selenium.getValue("//div[17]/div/table/tbody/tr[9]/td/select"), "162");
  			verifyEquals(selenium.getValue("//div[17]/div/table/tbody/tr[10]/td/select"), "167");
  			verifyEquals(selenium.getValue("//div[17]/div/table/tbody/tr[11]/td/select"), "172");
  			verifyEquals(selenium.getValue("//div[17]/div/table/tbody/tr[12]/td/select"), "177");
  			verifyEquals(selenium.getValue("//div[17]/div/table/tbody/tr[13]/td/select"), "181");
  			verifyEquals(selenium.getValue("//div[17]/div/table/tbody/tr[14]/td/select"), "186");
  			verifyEquals(selenium.getValue("//div[17]/div/table/tbody/tr[15]/td/select"), "188");
  			verifyEquals(selenium.getValue("//div[17]/div/table/tbody/tr[16]/td/select"), "191");
  			verifyEquals(selenium.getValue("//div[17]/div/table/tbody/tr[17]/td/select"), "197");
  			verifyEquals(selenium.getValue("//div[17]/div/table/tbody/tr[18]/td/select"), "204");
  			verifyEquals(selenium.getValue("//div[17]/div/table/tbody/tr[19]/td/select"), "209");
  			verifyEquals(selenium.getValue("//div[17]/div/table/tbody/tr[20]/td/select"), "92");
  			verifyEquals(selenium.getValue("//div[17]/div/table/tbody/tr[21]/td/select"), "89");
  			verifyEquals(selenium.getValue("//div[17]/div/table/tbody/tr[22]/td/select"), "218");
  			verifyEquals(selenium.getValue("//div[17]/div/table/tbody/tr[23]/td/select"), "221");
  			verifyEquals(selenium.getValue("//div[17]/div/table/tbody/tr[24]/td/select"), "227");
  			verifyEquals(selenium.getValue("//div[17]/div/table/tbody/tr[26]/td/select"), "235");
  			verifyEquals(selenium.getValue("//div[17]/div/table/tbody/tr[27]/td/select"), "240");
  			verifyEquals(selenium.getValue("//div[17]/div/table/tbody/tr[28]/td/select"), "243");
  			verifyEquals(selenium.getValue("//div[17]/div/table[2]/tbody/tr/td/select"), "249");
  			verifyEquals(selenium.getValue("//div[17]/div/table[2]/tbody/tr[2]/td/select"), "96");
  			verifyEquals(selenium.getValue("//div[17]/div/table[2]/tbody/tr[3]/td/select"), "259");
  			verifyEquals(selenium.getValue("//div[17]/div/table[2]/tbody/tr[4]/td/select"), "261");
  			verifyEquals(selenium.getValue("//div[17]/div/table[2]/tbody/tr[5]/td/select"), "142");
  			verifyEquals(selenium.getValue("//div[17]/div/table[2]/tbody/tr[6]/td/select"), "268");
  			verifyEquals(selenium.getValue("//div[17]/div/table[2]/tbody/tr[7]/td/select"), "273");
  			verifyEquals(selenium.getValue("//div[17]/div/table[2]/tbody/tr[8]/td/select"), "136");
  			verifyEquals(selenium.getValue("//div[17]/div/table[2]/tbody/tr[9]/td/select"), "101");
  			verifyEquals(selenium.getValue("//div[17]/div/table[2]/tbody/tr[10]/td/select"), "278");
  			verifyEquals(selenium.getValue("//div[17]/div/table[2]/tbody/tr[11]/td/select"), "284");
  			verifyEquals(selenium.getValue("//div[17]/div/table[2]/tbody/tr[12]/td/select"), "288");
  			verifyEquals(selenium.getValue("//div[17]/div/table[2]/tbody/tr[13]/td/select"), "294");
  			verifyEquals(selenium.getValue("//div[17]/div/table[2]/tbody/tr[14]/td/select"), "299");
  			verifyEquals(selenium.getValue("//div[17]/div/table[2]/tbody/tr[15]/td/select"), "304");
  			verifyEquals(selenium.getValue("//div[17]/div/table[2]/tbody/tr[16]/td/select"), "310");
  			verifyEquals(selenium.getValue("//div[17]/div/table[2]/tbody/tr[17]/td/select"), "316");
  			verifyEquals(selenium.getValue("//div[17]/div/table[2]/tbody/tr[18]/td/select"), "320");
  			verifyEquals(selenium.getValue("//div[17]/div/table[2]/tbody/tr[19]/td/select"), "326");
  			verifyEquals(selenium.getValue("//div[17]/div/table[2]/tbody/tr[20]/td/select"), "329");
  			verifyEquals(selenium.getValue("//div[17]/div/table[2]/tbody/tr[21]/td/select"), "335");
  			verifyEquals(selenium.getValue("//div[17]/div/table[2]/tbody/tr[22]/td/select"), "340");
  			verifyEquals(selenium.getValue("//div[17]/div/table[2]/tbody/tr[23]/td/select"), "345");
  			verifyEquals(selenium.getValue("//div[17]/div/table[2]/tbody/tr[24]/td/select"), "347");
  			verifyEquals(selenium.getValue("//div[17]/div/table[2]/tbody/tr[25]/td/select"), "13");
  			verifyEquals(selenium.getValue("//div[17]/div/table[2]/tbody/tr[26]/td/select"), "359");
  			verifyEquals(selenium.getValue("//div[17]/div/table[2]/tbody/tr[27]/td/select"), "369");
  			verifyEquals(selenium.getValue("//div[17]/div/table[2]/tbody/tr[28]/td/select"), "364");
  			
  		    //Logout
  			Thread.sleep(8000);
  			selenium.clickAt("link=Logout", "");
  			Thread.sleep(5000);
  			for (int second1 = 0;; second1++) {
  				if (second1 >= 60) fail("timeout");
  				try { if (selenium.isElementPresent("id=loginBox")) break; } catch (Exception e) {}
  				Thread.sleep(1000);}
  		}

	     
        try {
            Thread.sleep(24579);
        } catch (InterruptedException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
    }   
}