package iT_Edit_Ex_Release;

import org.testng.annotations.*;
import com.thoughtworks.selenium.FlashSelenium;
import FunctionLibrary.Common;
import com.thoughtworks.selenium.SeleneseTestBase;
import com.thoughtworks.selenium.Selenium;

@Test
public class EditExRelease extends SeleneseTestBase{

	public Selenium selenium;
	@BeforeClass
	public void loginUser() throws Exception{
		selenium=Common.CsetUp();
		Common.open(selenium);
			}
		public void userLogin() throws Exception{
        
		System.out.println("userlogin start");
         
    
      //  Login   
		Thread.sleep(7000);
		selenium.type("name=username", "synergy");
		Thread.sleep(2000);
		selenium.type("name=password", "Orchard09");
		Thread.sleep(2000);
		selenium.clickAt("//input[@type='submit']", "");
		Thread.sleep(20579);
		verifyTrue(selenium.isElementPresent("id=contentArea"));
		verifyTrue(selenium.isElementPresent("css=input[name=\"varSearchString\"]"));
		System.out.println("userlogin end");

	// 	OpenRelease
		System.out.println("OpenRelease start");

		Thread.sleep(10000);
		verifyTrue(selenium.isElementPresent("css=input[name=\"varSearchString\"]"));
		selenium.type("css=input[name=\"varSearchString\"]", "7123");
		Thread.sleep(2000);
		selenium.selectWindow("null");
		verifyTrue(selenium.isElementPresent("//input[3]"));
		selenium.click("//input[3]");
		Thread.sleep(8000);
		for (int second = 0;; second++) {
			if (second >= 60) fail("timeout");
			try { if (selenium.isElementPresent("id=item")) break; } catch (Exception e) {}
			Thread.sleep(1000);
		}

		Thread.sleep(2000);
		verifyTrue(selenium.isElementPresent("//div[4]/table/tbody/tr[2]/td/a"));
		verifyEquals(selenium.getText("css=h3"), "Label Results - Viewing 1 of 1");
		selenium.click("link=7123");
		Thread.sleep(30000);
		for (int second = 0;; second++) {
			if (second >= 60) fail("timeout");
			try { if (selenium.isElementPresent("//div/ul/li[9]/a")) break; } catch (Exception e) {}
			Thread.sleep(1000);
			System.out.println("OpenRelease End");


	// 	Edit_Ex_Release
			System.out.println("Edit_Ex_Release Start");
			verifyTrue(selenium.isElementPresent("//div/ul/li[9]/a"));
			selenium.clickAt("//div/ul/li[9]/a", "");
			Thread.sleep(12579);
			verifyTrue(selenium.isElementPresent("//div[@id='contentArea']/div[7]/form/table/tbody/tr[2]/td[4]/a"));
			selenium.clickAt("//div[@id='contentArea']/div[7]/form/table/tbody/tr[2]/td[4]/a", "");
			Thread.sleep(35000);
			verifyTrue(selenium.isElementPresent("css=select[name=\"product_type_id\"]"));
			String ProductType = selenium.getEval("'Movie'");
			System.out.println("74");
			verifyTrue(selenium.isElementPresent("css=select[name=\"product_type_id\"]"));
			selenium.select("css=select[name=\"product_type_id\"]", selenium.getEval("'" + ProductType + "'"));
			String ReleaseMetaLanguage = selenium.getEval("'French'");
			System.out.println("78");
			verifyTrue(selenium.isElementPresent("css=select[name=\"meta_language\"]"));
			selenium.select("css=select[name=\"meta_language\"]", selenium.getEval("'" + ReleaseMetaLanguage + "'"));
			String ReleaseName = selenium.getEval("'Selenium_Release_'+885686234877");
			verifyTrue(selenium.isElementPresent("css=input[name=\"release_name_req\"]"));
			selenium.type("css=input[name=\"release_name_req\"]", selenium.getEval("'" + ReleaseName + "'"));
			String LabelImprint = selenium.getEval("'sony records'+(new Date().getDate())");
			System.out.println("85");
			verifyTrue(selenium.isElementPresent("css=input[name=\"label\"]"));
			selenium.type("css=input[name=\"label\"]", selenium.getEval("'" + LabelImprint + "'"));
			String ManufacturersUPC = selenium.getEval("''+(new Date().getDate())");
			verifyTrue(selenium.isElementPresent("css=input[name=\"manufacturer_upc\"]"));
			selenium.type("css=input[name=\"manufacturer_upc\"]", selenium.getEval("'" + ManufacturersUPC + "'"));
			String Line = selenium.getEval("'2012 VAPI'+(new Date().getHours())");
			verifyTrue(selenium.isElementPresent("css=input[name=\"c_line\"]"));
			selenium.type("css=input[name=\"c_line\"]", selenium.getEval("'" + Line + "'"));
			System.out.println("93");
			String DescriptionSynopsis = selenium.getEval("'Describe'+(new Date().getTime())");
			verifyTrue(selenium.isElementPresent("css=textarea[name=\"description\"]"));
			selenium.type("css=textarea[name=\"description\"]", selenium.getEval("'" + DescriptionSynopsis + "'"));
			System.out.println("98");
			String NotForDistribution = selenium.getEval("'Y'");
			verifyTrue(selenium.isElementPresent("css=select[name=\"not_for_distribution\"]"));
			selenium.select("css=select[name=\"not_for_distribution\"]", selenium.getEval("'" + NotForDistribution + "'"));
			String TributeByUnknownArtist = selenium.getEval("'Y'");
			verifyTrue(selenium.isElementPresent("css=select[name=\"unknown_artist\"]"));
			selenium.select("css=select[name=\"unknown_artist\"]", selenium.getEval("'" + TributeByUnknownArtist + "'"));
			String PromoUPC = selenium.getEval("''+(new Date().getDate())");
			verifyTrue(selenium.isElementPresent("css=input[name=\"promo_upc\"]"));
			selenium.type("css=input[name=\"promo_upc\"]", selenium.getEval("'" + PromoUPC + "'"));
			String Language = selenium.getEval("'English'");
			verifyTrue(selenium.isElementPresent("css=select[name=\"language_id\"]"));
			selenium.select("css=select[name=\"language_id\"]", selenium.getEval("'" + Language + "'"));
			String SubtitleLanguage = selenium.getEval("'French'");
			verifyTrue(selenium.isElementPresent("css=select[name=\"subtitle_language_id\"]"));
			selenium.select("css=select[name=\"subtitle_language_id\"]", selenium.getEval("'" + SubtitleLanguage + "'"));
			String InitialPriority = selenium.getEval("'2'");
			verifyTrue(selenium.isElementPresent("css=select[name=\"priority\"]"));
			selenium.select("css=select[name=\"priority\"]", selenium.getEval("'" + InitialPriority + "'"));
			String NewRelease = selenium.getEval("'Direct To Video'");
			verifyTrue(selenium.isElementPresent("css=select[name=\"new_release\"]"));
			selenium.select("css=select[name=\"new_release\"]", selenium.getEval("'" + NewRelease + "'"));
			String PreOrderDate = selenium.getEval("'Immediate'");
			verifyTrue(selenium.isElementPresent("css=select[name=\"prmPreorderType\"]"));
			selenium.select("css=select[name=\"prmPreorderType\"]", selenium.getEval("'" + PreOrderDate + "'"));
			String OrchardArtist = selenium.getEval("'dasda'");
			verifyTrue(selenium.isElementPresent("css=select[name=\"prmArtistID\"]"));
			selenium.select("css=select[name=\"prmArtistID\"]", selenium.getEval("'" + OrchardArtist + "'"));
			String ReleaseDate = selenium.getEval("'2012-03-31'");
			verifyTrue(selenium.isElementPresent("css=input[name=\"release_date\"]"));
			selenium.type("css=input[name=\"release_date\"]", selenium.getEval("'" + ReleaseDate + "'"));
			String SaleStartDate = selenium.getEval("'2012-03-19'");
			verifyTrue(selenium.isElementPresent("css=input[name=\"sale_start_date\"]"));
			selenium.type("css=input[name=\"sale_start_date\"]", selenium.getEval("'" + SaleStartDate + "'"));
			String VODStartDate = selenium.getEval("'2012-05-03'");
			verifyTrue(selenium.isElementPresent("css=input[name=\"vod_start_date\"]"));
			selenium.type("css=input[name=\"vod_start_date\"]", selenium.getEval("'" + SaleStartDate + "'"));
			String LabelCatalog = selenium.getEval("'2012 synergy'");
			verifyTrue(selenium.isElementPresent("css=input[name=\"VCN\"]"));
			selenium.type("css=input[name=\"VCN\"]", selenium.getEval("'" + LabelCatalog + "'"));
			String Distribution = selenium.getEval("'phys/digital'");
			verifyTrue(selenium.isElementPresent("css=select[name=\"distribution\"]"));
			selenium.select("css=select[name=\"distribution\"]", selenium.getEval("'" + Distribution + "'"));
			String PrimaryGenre = selenium.getEval("'Animation'");
			verifyTrue(selenium.isElementPresent("css=#primary_genre_id"));
			selenium.select("css=#primary_genre_id", selenium.getEval("'" + PrimaryGenre + "'"));
			String ofPromos = selenium.getEval("'adult'");
			verifyTrue(selenium.isElementPresent("css=input[name=\"promos_number\"]"));
			selenium.type("css=input[name=\"promos_number\"]", selenium.getEval("'" + ofPromos + "'"));
			String PublicDomaininEurope = selenium.getEval("'Y'");
			verifyTrue(selenium.isElementPresent("css=select[name=\"europe_public_domain\"]"));
			selenium.select("css=select[name=\"europe_public_domain\"]", selenium.getEval("'" + PublicDomaininEurope + "'"));
			String ProductFormat = selenium.getEval("'Boxset'");
			verifyTrue(selenium.isElementPresent("css=select[name=\"product_format\"]"));
			selenium.select("css=select[name=\"product_format\"]", selenium.getEval("'" + ProductFormat + "'"));
			String Format = selenium.getEval("'DVD'");
			verifyTrue(selenium.isElementPresent("css=#format"));
			selenium.select("css=#format", selenium.getEval("'" + Format + "'"));
			String Karaoke = selenium.getEval("'Y'");
			verifyTrue(selenium.isElementPresent("css=select[name=\"karaoke\"]"));
			selenium.select("css=select[name=\"karaoke\"]", selenium.getEval("'" + Karaoke + "'"));
			String DigitalOnly = selenium.getEval("'Y'");
			verifyTrue(selenium.isElementPresent("css=select[name=\"digital_only\"]"));
			selenium.select("css=select[name=\"digital_only\"]", selenium.getEval("'" + DigitalOnly + "'"));
			String Version = selenium.getEval("'Version'+(new Date().getDate())");
			verifyTrue(selenium.isElementPresent("css=input[name=\"version\"]"));
			selenium.type("css=input[name=\"version\"]", selenium.getEval("'" + Version + "'"));
			String ShortSynopsis = selenium.getEval("'Version'+(new Date().getDate())");
			verifyTrue(selenium.isElementPresent("name=short_synopsis_film"));
			selenium.type("name=short_synopsis_film", selenium.getEval("'" + ShortSynopsis + "'"));
			String AMGID = selenium.getEval("'Version'+(new Date().getDate())");
			verifyTrue(selenium.isElementPresent("css=input[name=\"amd_id_film\"]"));
			selenium.type("css=input[name=\"amd_id_film\"]", selenium.getEval("'" + AMGID + "'"));
			String TheatricalReleaseDate = selenium.getEval("'2012-03-19'");
			verifyTrue(selenium.isElementPresent("css=input[name=\"theatrical_release_date_film\"]"));
			selenium.type("css=input[name=\"theatrical_release_date_film\"]", selenium.getEval("'" + TheatricalReleaseDate + "'"));
			String PhysicalReleaseDate = selenium.getEval("'2012-03-19'");
			verifyTrue(selenium.isElementPresent("css=input[name=\"physical_release_date\"]"));
			selenium.type("css=input[name=\"physical_release_date\"]", selenium.getEval("'" + PhysicalReleaseDate + "'"));
			String Subtype = selenium.getEval("'Short'");
			verifyTrue(selenium.isElementPresent("css=select[name=\"film_subtype_film\"]"));
			selenium.select("css=select[name=\"film_subtype_film\"]", selenium.getEval("'" + Subtype + "'"));
			String CountryofOrigin = selenium.getEval("'Angola'");
			verifyTrue(selenium.isElementPresent("css=select[name=\"country_of_origin_film\"]"));
			selenium.select("css=select[name=\"country_of_origin_film\"]", selenium.getEval("'" + CountryofOrigin + "'"));
			String Channel = selenium.getEval("'Action'");
			verifyTrue(selenium.isElementPresent("css=select[name=\"channel_id_film\"]"));
			selenium.select("css=select[name=\"channel_id_film\"]", selenium.getEval("'" + Channel + "'"));
			String ProductionCo = selenium.getEval("'Action'");
			verifyTrue(selenium.isElementPresent("css=input[name=\"production_co_film\"]"));
			selenium.type("css=input[name=\"production_co_film\"]", selenium.getEval("'" + ProductionCo + "'"));
			String Brand = selenium.getEval("'Action'");
			verifyTrue(selenium.isElementPresent("css=input[name=\"brand_film\"]"));
			selenium.type("css=input[name=\"brand_film\"]", selenium.getEval("'" + Brand + "'"));
			String TMSMovieID = selenium.getEval("'578'+(new Date().getSeconds())");
			verifyTrue(selenium.isElementPresent("css=input[name=\"tms_id_film\"]"));
			selenium.type("css=input[name=\"tms_id_film\"]", selenium.getEval("'" + TMSMovieID + "'"));
			String ARMovies = selenium.getEval("'578'+(new Date().getSeconds())");
			verifyTrue(selenium.isElementPresent("css=input[name=\"reasons_film[ar_movies]\"]"));
			selenium.type("css=input[name=\"reasons_film[ar_movies]\"]", selenium.getEval("'" + ARMovies + "'"));
			String AUOFLC = selenium.getEval("'578'+(new Date().getSeconds())");
			verifyTrue(selenium.isElementPresent("css=input[name=\"reasons_film[au_oflc]\"]"));
			selenium.type("css=input[name=\"reasons_film[au_oflc]\"]", selenium.getEval("'" + AUOFLC + "'"));
			String FSK = selenium.getEval("'578'+(new Date().getSeconds())");
			verifyTrue(selenium.isElementPresent("css=input[name=\"reasons_film[fsk]\"]"));
			selenium.type("css=input[name=\"reasons_film[fsk]\"]", selenium.getEval("'" + FSK + "'"));
			String BEMovies = selenium.getEval("'578'+(new Date().getSeconds())");
			verifyTrue(selenium.isElementPresent("css=input[name=\"reasons_film[be_movies]\"]"));
			selenium.type("css=input[name=\"reasons_film[be_movies]\"]", selenium.getEval("'" + BEMovies + "'"));
			String BOMovies = selenium.getEval("'578'+(new Date().getSeconds())");
			verifyTrue(selenium.isElementPresent("css=input[name=\"reasons_film[bo_movies]\"]"));
			selenium.type("css=input[name=\"reasons_film[bo_movies]\"]", selenium.getEval("'" + BOMovies + "'"));
			String BRMovies = selenium.getEval("'578'+(new Date().getSeconds())");
			verifyTrue(selenium.isElementPresent("css=input[name=\"reasons_film[br_movies]\"]"));
			selenium.type("css=input[name=\"reasons_film[br_movies]\"]", selenium.getEval("'" + BRMovies + "'"));
			String BGMovies = selenium.getEval("'578'+(new Date().getSeconds())");
			verifyTrue(selenium.isElementPresent("css=input[name=\"reasons_film[bg_movies]\"]"));
			selenium.type("css=input[name=\"reasons_film[bg_movies]\"]", selenium.getEval("'" + BGMovies + "'"));
			String CACHVRS = selenium.getEval("'578'+(new Date().getSeconds())");
			verifyTrue(selenium.isElementPresent("css=input[name=\"reasons_film[ca_chvrs]\"]"));
			selenium.type("css=input[name=\"reasons_film[ca_chvrs]\"]", selenium.getEval("'" + CACHVRS + "'"));
			String CLMovies = selenium.getEval("'578'+(new Date().getSeconds())");
			verifyTrue(selenium.isElementPresent("css=input[name=\"reasons_film[cl_movies]\"]"));
			selenium.type("css=input[name=\"reasons_film[cl_movies]\"]", selenium.getEval("'" + CLMovies + "'"));
			String COMovies = selenium.getEval("'578'+(new Date().getSeconds())");
			verifyTrue(selenium.isElementPresent("css=input[name=\"reasons_film[co_movies]\"]"));
			selenium.type("css=input[name=\"reasons_film[co_movies]\"]", selenium.getEval("'" + COMovies + "'"));
			String CRMovies = selenium.getEval("'578'+(new Date().getSeconds())");
			verifyTrue(selenium.isElementPresent("css=input[name=\"reasons_film[cr_movies]\"]"));
			selenium.type("css=input[name=\"reasons_film[cr_movies]\"]", selenium.getEval("'" + CRMovies + "'"));
			String CYMovies = selenium.getEval("'578'+(new Date().getSeconds())");
			verifyTrue(selenium.isElementPresent("css=input[name=\"reasons_film[cy_movies]\"]"));
			selenium.type("css=input[name=\"reasons_film[cy_movies]\"]", selenium.getEval("'" + CYMovies + "'"));
			String CZMovies = selenium.getEval("'578'+(new Date().getSeconds())");
			verifyTrue(selenium.isElementPresent("css=input[name=\"reasons_film[cz_movies]\"]"));
			selenium.type("css=input[name=\"reasons_film[cz_movies]\"]", selenium.getEval("'" + CZMovies + "'"));
			String DKMovies = selenium.getEval("'578'+(new Date().getSeconds())");
			verifyTrue(selenium.isElementPresent("css=input[name=\"reasons_film[dk_movies]\"]"));
			selenium.type("css=input[name=\"reasons_film[dk_movies]\"]", selenium.getEval("'" + DKMovies + "'"));
			String DOMovies = selenium.getEval("'578'+(new Date().getSeconds())");
			verifyTrue(selenium.isElementPresent("css=input[name=\"reasons_film[do_movies]\"]"));
			selenium.type("css=input[name=\"reasons_film[do_movies]\"]", selenium.getEval("'" + DOMovies + "'"));
			String ECMovies = selenium.getEval("'578'+(new Date().getSeconds())");
			verifyTrue(selenium.isElementPresent("css=input[name=\"reasons_film[ec_movies]\"]"));
			selenium.type("css=input[name=\"reasons_film[ec_movies]\"]", selenium.getEval("'" + ECMovies + "'"));
			String SVMovies = selenium.getEval("'578'+(new Date().getSeconds())");
			verifyTrue(selenium.isElementPresent("css=input[name=\"reasons_film[sv_movies]\"]"));
			selenium.type("css=input[name=\"reasons_film[sv_movies]\"]", selenium.getEval("'" + SVMovies + "'"));
			String EEMovies = selenium.getEval("'578'+(new Date().getSeconds())");
			verifyTrue(selenium.isElementPresent("css=input[name=\"reasons_film[ee_movies]\"]"));
			selenium.type("css=input[name=\"reasons_film[ee_movies]\"]", selenium.getEval("'" + EEMovies + "'"));
			String FIMovies = selenium.getEval("'578'+(new Date().getSeconds())");
			verifyTrue(selenium.isElementPresent("css=input[name=\"reasons_film[fi_movies]\"]"));
			selenium.type("css=input[name=\"reasons_film[fi_movies]\"]", selenium.getEval("'" + FIMovies + "'"));
			String FRMovies = selenium.getEval("'578'+(new Date().getSeconds())");
			verifyTrue(selenium.isElementPresent("css=input[name=\"reasons_film[fr_cnc]\"]"));
			selenium.type("css=input[name=\"reasons_film[fr_cnc]\"]", selenium.getEval("'" + FRMovies + "'"));
			String DEFSK = selenium.getEval("'578'+(new Date().getSeconds())");
			verifyTrue(selenium.isElementPresent("css=input[name=\"reasons_film[de-fsk]\"]"));
			selenium.type("css=input[name=\"reasons_film[de-fsk]\"]", selenium.getEval("'" + DEFSK + "'"));
			String GRMovies = selenium.getEval("'578'+(new Date().getSeconds())");
			verifyTrue(selenium.isElementPresent("css=input[name=\"reasons_film[gr_movies]\"]"));
			selenium.type("css=input[name=\"reasons_film[gr_movies]\"]", selenium.getEval("'" + GRMovies + "'"));
			String GTMovies = selenium.getEval("'578'+(new Date().getSeconds())");
			verifyTrue(selenium.isElementPresent("css=input[name=\"reasons_film[gt_movies]\"]"));
			selenium.type("css=input[name=\"reasons_film[gt_movies]\"]", selenium.getEval("'" + GTMovies + "'"));
			String GYMovies = selenium.getEval("'578'+(new Date().getSeconds())");
			verifyTrue(selenium.isElementPresent("css=input[name=\"reasons_film[gy_movies]\"]"));
			selenium.type("css=input[name=\"reasons_film[gy_movies]\"]", selenium.getEval("'" + GYMovies + "'"));
			String HNMovies = selenium.getEval("'578'+(new Date().getSeconds())");
			verifyTrue(selenium.isElementPresent("css=input[name=\"reasons_film[hn_movies]\"]"));
			selenium.type("css=input[name=\"reasons_film[hn_movies]\"]", selenium.getEval("'" + HNMovies + "'"));
			String HUMovies = selenium.getEval("'578'+(new Date().getSeconds())");
			verifyTrue(selenium.isElementPresent("css=input[name=\"reasons_film[hu_movies]\"]"));
			selenium.type("css=input[name=\"reasons_film[hu_movies]\"]", selenium.getEval("'" + HUMovies + "'"));
			String IEIfco = selenium.getEval("'578'+(new Date().getSeconds())");
			verifyTrue(selenium.isElementPresent("css=input[name=\"reasons_film[ie_ifco]\"]"));
			selenium.type("css=input[name=\"reasons_film[ie_ifco]\"]", selenium.getEval("'" + IEIfco + "'"));
			String ITMovies = selenium.getEval("'578'+(new Date().getSeconds())");
			verifyTrue(selenium.isElementPresent("css=input[name=\"reasons_film[it_movies]\"]"));
			selenium.type("css=input[name=\"reasons_film[it_movies]\"]", selenium.getEval("'" + ITMovies + "'"));
			String JMMovies = selenium.getEval("'578'+(new Date().getSeconds())");
			verifyTrue(selenium.isElementPresent("css=input[name=\"reasons_film[jm_movies]\"]"));
			selenium.type("css=input[name=\"reasons_film[jm_movies]\"]", selenium.getEval("'" + JMMovies + "'"));
			String JPEIRIN = selenium.getEval("'578'+(new Date().getSeconds())");
			verifyTrue(selenium.isElementPresent("css=input[name=\"reasons_film[jp_eirin]\"]"));
			selenium.type("css=input[name=\"reasons_film[jp_eirin]\"]", selenium.getEval("'" + JPEIRIN + "'"));
			String LVMovies = selenium.getEval("'578'+(new Date().getSeconds())");
			verifyTrue(selenium.isElementPresent("css=input[name=\"reasons_film[lv_movies]\"]"));
			selenium.type("css=input[name=\"reasons_film[lv_movies]\"]", selenium.getEval("'" + LVMovies + "'"));
			String LTMovies = selenium.getEval("'578'+(new Date().getSeconds())");
			verifyTrue(selenium.isElementPresent("css=input[name=\"reasons_film[lt_movies]\"]"));
			selenium.type("css=input[name=\"reasons_film[lt_movies]\"]", selenium.getEval("'" + LTMovies + "'"));
			String LUMovies = selenium.getEval("'578'+(new Date().getSeconds())");
			verifyTrue(selenium.isElementPresent("css=input[name=\"reasons_film[lu_movies]\"]"));
			selenium.type("css=input[name=\"reasons_film[lu_movies]\"]", selenium.getEval("'" + LUMovies + "'"));
			String MTMovies = selenium.getEval("'578'+(new Date().getSeconds())");
			verifyTrue(selenium.isElementPresent("css=input[name=\"reasons_film[mt_movies]\"]"));
			selenium.type("css=input[name=\"reasons_film[mt_movies]\"]", selenium.getEval("'" + MTMovies + "'"));
			String MXMovies = selenium.getEval("'578'+(new Date().getSeconds())");
			verifyTrue(selenium.isElementPresent("css=input[name=\"reasons_film[mx_movies]\"]"));
			selenium.type("css=input[name=\"reasons_film[mx_movies]\"]", selenium.getEval("'" + MXMovies + "'"));
			String NLMovies = selenium.getEval("'578'+(new Date().getSeconds())");
			verifyTrue(selenium.isElementPresent("css=input[name=\"reasons_film[nl_movies]\"]"));
			selenium.type("css=input[name=\"reasons_film[nl_movies]\"]", selenium.getEval("'" + NLMovies + "'"));
			String NZOflc = selenium.getEval("'578'+(new Date().getSeconds())");
			verifyTrue(selenium.isElementPresent("css=input[name=\"reasons_film[nz_oflc]\"]"));
			selenium.type("css=input[name=\"reasons_film[nz_oflc]\"]", selenium.getEval("'" + NZOflc + "'"));
			String NIMovies = selenium.getEval("'578'+(new Date().getSeconds())");
			verifyTrue(selenium.isElementPresent("css=input[name=\"reasons_film[ni_movies]\"]"));
			selenium.type("css=input[name=\"reasons_film[ni_movies]\"]", selenium.getEval("'" + NIMovies + "'"));
			String NOMovies = selenium.getEval("'578'+(new Date().getSeconds())");
			verifyTrue(selenium.isElementPresent("css=input[name=\"reasons_film[no_movies]\"]"));
			selenium.type("css=input[name=\"reasons_film[no_movies]\"]", selenium.getEval("'" + NOMovies + "'"));
			String PAMovies = selenium.getEval("'578'+(new Date().getSeconds())");
			verifyTrue(selenium.isElementPresent("css=input[name=\"reasons_film[pa_movies]\"]"));
			selenium.type("css=input[name=\"reasons_film[pa_movies]\"]", selenium.getEval("'" + PAMovies + "'"));
			String PYMovies = selenium.getEval("'578'+(new Date().getSeconds())");
			verifyTrue(selenium.isElementPresent("css=input[name=\"reasons_film[py_movies]\"]"));
			selenium.type("css=input[name=\"reasons_film[py_movies]\"]", selenium.getEval("'" + PYMovies + "'"));
			String PEMovies = selenium.getEval("'578'+(new Date().getSeconds())");
			verifyTrue(selenium.isElementPresent("css=input[name=\"reasons_film[pe_movies]\"]"));
			selenium.type("css=input[name=\"reasons_film[pe_movies]\"]", selenium.getEval("'" + PEMovies + "'"));
			String PLMovies = selenium.getEval("'578'+(new Date().getSeconds())");
			verifyTrue(selenium.isElementPresent("css=input[name=\"reasons_film[pl_movies]\"]"));
			selenium.type("css=input[name=\"reasons_film[pl_movies]\"]", selenium.getEval("'" + PLMovies + "'"));
			String PTMovies = selenium.getEval("'578'+(new Date().getSeconds())");
			verifyTrue(selenium.isElementPresent("css=input[name=\"reasons_film[pt_movies]\"]"));
			selenium.type("css=input[name=\"reasons_film[pt_movies]\"]", selenium.getEval("'" + PTMovies + "'"));
			String CARcq = selenium.getEval("'578'+(new Date().getSeconds())");
			verifyTrue(selenium.isElementPresent("css=input[name=\"reasons_film[ca-rcq]\"]"));
			selenium.type("css=input[name=\"reasons_film[ca-rcq]\"]", selenium.getEval("'" + CARcq + "'"));
			String ROMovies = selenium.getEval("'578'+(new Date().getSeconds())");
			verifyTrue(selenium.isElementPresent("css=input[name=\"reasons_film[ro_movies]\"]"));
			selenium.type("css=input[name=\"reasons_film[ro_movies]\"]", selenium.getEval("'" + ROMovies + "'"));
			selenium.selectWindow("null");
			String SKMovies = selenium.getEval("'578'+(new Date().getSeconds())");
			verifyTrue(selenium.isElementPresent("css=input[name=\"reasons_film[sk_movies]\"]"));
			selenium.type("css=input[name=\"reasons_film[sk_movies]\"]", selenium.getEval("'" + SKMovies + "'"));
			String SIMovies = selenium.getEval("'578'+(new Date().getSeconds())");
			verifyTrue(selenium.isElementPresent("css=input[name=\"reasons_film[si_movies]\"]"));
			selenium.type("css=input[name=\"reasons_film[si_movies]\"]", selenium.getEval("'" + SIMovies + "'"));
			String ESMovies = selenium.getEval("'578'+(new Date().getSeconds())");
			verifyTrue(selenium.isElementPresent("css=input[name=\"reasons_film[es_movies]\"]"));
			selenium.type("css=input[name=\"reasons_film[es_movies]\"]", selenium.getEval("'" + ESMovies + "'"));
			String SRMovies = selenium.getEval("'578'+(new Date().getSeconds())");
			verifyTrue(selenium.isElementPresent("css=input[name=\"reasons_film[sr_movies]\"]"));
			selenium.type("css=input[name=\"reasons_film[sr_movies]\"]", selenium.getEval("'" + SRMovies + "'"));
			String CHMovies = selenium.getEval("'578'+(new Date().getSeconds())");
			verifyTrue(selenium.isElementPresent("css=input[name=\"reasons_film[ch_movies]\"]"));
			selenium.type("css=input[name=\"reasons_film[ch_movies]\"]", selenium.getEval("'" + CHMovies + "'"));
			String SEMovies = selenium.getEval("'578'+(new Date().getSeconds())");
			verifyTrue(selenium.isElementPresent("css=input[name=\"reasons_film[se_movies]\"]"));
			selenium.type("css=input[name=\"reasons_film[se_movies]\"]", selenium.getEval("'" + SEMovies + "'"));
			String BBFC = selenium.getEval("'578'+(new Date().getSeconds())");
			verifyTrue(selenium.isElementPresent("css=input[name=\"reasons_film[bbfc]\"]"));
			selenium.type("css=input[name=\"reasons_film[bbfc]\"]", selenium.getEval("'" + BBFC + "'"));
			String UYMovies = selenium.getEval("'578'+(new Date().getSeconds())");
			verifyTrue(selenium.isElementPresent("css=input[name=\"reasons_film[uy_movies]\"]"));
			selenium.type("css=input[name=\"reasons_film[uy_movies]\"]", selenium.getEval("'" + UYMovies + "'"));
			String MPAA = selenium.getEval("'578'+(new Date().getSeconds())");
			verifyTrue(selenium.isElementPresent("css=input[name=\"reasons_film[mpaa]\"]"));
			selenium.type("css=input[name=\"reasons_film[mpaa]\"]", selenium.getEval("'" + MPAA + "'"));
			String VEMovies = selenium.getEval("'578'+(new Date().getSeconds())");
			verifyTrue(selenium.isElementPresent("css=input[name=\"reasons_film[ve_movies]\"]"));
			selenium.type("css=input[name=\"reasons_film[ve_movies]\"]", selenium.getEval("'" + VEMovies + "'"));
			String ArgentinaARMovies = selenium.getEval("'ATP'");
			verifyTrue(selenium.isElementPresent("//div[17]/div/table/tbody/tr/td/select"));
			selenium.select("//div[17]/div/table/tbody/tr/td/select", selenium.getEval("'" + ArgentinaARMovies + "'"));
			String AustraliaAUOFLC = selenium.getEval("'G'");
			verifyTrue(selenium.isElementPresent("//div[17]/div/table/tbody/tr[2]/td/select"));
			selenium.select("//div[17]/div/table/tbody/tr[2]/td/select", selenium.getEval("'" + AustraliaAUOFLC + "'"));
			String AustriaFSK = selenium.getEval("'ab 0 Jahren'");
			verifyTrue(selenium.isElementPresent("//div[17]/div/table/tbody/tr[3]/td/select"));
			selenium.select("//div[17]/div/table/tbody/tr[3]/td/select", selenium.getEval("'" + AustriaFSK + "'"));
			String BelgiumBEMovies = selenium.getEval("'12'");
			verifyTrue(selenium.isElementPresent("//div[17]/div/table/tbody/tr[4]/td/select"));
			selenium.select("//div[17]/div/table/tbody/tr[4]/td/select", selenium.getEval("'" + BelgiumBEMovies + "'"));
			String BoliviaBOMovies = selenium.getEval("'14'");
			verifyTrue(selenium.isElementPresent("//div[17]/div/table/tbody/tr[5]/td/select"));
			selenium.select("//div[17]/div/table/tbody/tr[5]/td/select", selenium.getEval("'" + BoliviaBOMovies + "'"));
			String BrazilBRMovies = selenium.getEval("'10'");
			verifyTrue(selenium.isElementPresent("//div[17]/div/table/tbody/tr[6]/td/select"));
			selenium.select("//div[17]/div/table/tbody/tr[6]/td/select", selenium.getEval("'" + BrazilBRMovies + "'"));
			String BulgariaBGMovies = selenium.getEval("'A'");
			verifyTrue(selenium.isElementPresent("//div[17]/div/table/tbody/tr[7]/td/select"));
			selenium.select("//div[17]/div/table/tbody/tr[7]/td/select", selenium.getEval("'" + BulgariaBGMovies + "'"));
			String CanadaCACHVRS = selenium.getEval("'14A'");
			verifyTrue(selenium.isElementPresent("//div[17]/div/table/tbody/tr[8]/td/select"));
			selenium.select("//div[17]/div/table/tbody/tr[8]/td/select", selenium.getEval("'" + CanadaCACHVRS + "'"));
			String ChileCLMovies = selenium.getEval("'14'");
			verifyTrue(selenium.isElementPresent("//div[17]/div/table/tbody/tr[9]/td/select"));
			selenium.select("//div[17]/div/table/tbody/tr[9]/td/select", selenium.getEval("'" + ChileCLMovies + "'"));
			String ColombiaCOMovies = selenium.getEval("'12'");
			verifyTrue(selenium.isElementPresent("//div[17]/div/table/tbody/tr[10]/td/select"));
			selenium.select("//div[17]/div/table/tbody/tr[10]/td/select", selenium.getEval("'" + ColombiaCOMovies + "'"));
			String CostaRicaCRMovies = selenium.getEval("'12'");
			verifyTrue(selenium.isElementPresent("//div[17]/div/table/tbody/tr[11]/td/select"));
			selenium.select("//div[17]/div/table/tbody/tr[11]/td/select", selenium.getEval("'" + CostaRicaCRMovies + "'"));
			String CostaRicaCRMoviesnew = selenium.getEval("'12'");
			verifyTrue(selenium.isElementPresent("//div[17]/div/table/tbody/tr[11]/td/select"));
			selenium.select("//div[17]/div/table/tbody/tr[11]/td/select", selenium.getEval("'" + CostaRicaCRMoviesnew + "'"));
			String CyprusCYMovies = selenium.getEval("'12'");
			verifyTrue(selenium.isElementPresent("//div[17]/div/table/tbody/tr[12]/td/select"));
			selenium.select("//div[17]/div/table/tbody/tr[12]/td/select", selenium.getEval("'" + CyprusCYMovies + "'"));
			String CzechRepublicCZMovies = selenium.getEval("'12+'");
			verifyTrue(selenium.isElementPresent("//div[17]/div/table/tbody/tr[13]/td/select"));
			selenium.select("//div[17]/div/table/tbody/tr[13]/td/select", selenium.getEval("'" + CzechRepublicCZMovies + "'"));
			String DenmarkDKMovies = selenium.getEval("'11'");
			verifyTrue(selenium.isElementPresent("//div[17]/div/table/tbody/tr[14]/td/select"));
			selenium.select("//div[17]/div/table/tbody/tr[14]/td/select", selenium.getEval("'" + DenmarkDKMovies + "'"));
			String DominicanRepublicDOMovies = selenium.getEval("'Todos'");
			verifyTrue(selenium.isElementPresent("//div[17]/div/table/tbody/tr[15]/td/select"));
			selenium.select("//div[17]/div/table/tbody/tr[15]/td/select", selenium.getEval("'" + DominicanRepublicDOMovies + "'"));
			String EcuadorECMovies = selenium.getEval("'12'");
			verifyTrue(selenium.isElementPresent("//div[17]/div/table/tbody/tr[16]/td/select"));
			selenium.select("//div[17]/div/table/tbody/tr[16]/td/select", selenium.getEval("'" + EcuadorECMovies + "'"));
			String EISalvadorSVMovies = selenium.getEval("'12'");
			verifyTrue(selenium.isElementPresent("//div[17]/div/table/tbody/tr[17]/td/select"));
			selenium.select("//div[17]/div/table/tbody/tr[17]/td/select", selenium.getEval("'" + EISalvadorSVMovies + "'"));
			String EstoniaEEMovies = selenium.getEval("'K12'");
			verifyTrue(selenium.isElementPresent("//div[17]/div/table/tbody/tr[18]/td/select"));
			selenium.select("//div[17]/div/table/tbody/tr[18]/td/select", selenium.getEval("'" + EstoniaEEMovies + "'"));
			String FinlandFIovies = selenium.getEval("'K-11'");
			verifyTrue(selenium.isElementPresent("//div[17]/div/table/tbody/tr[19]/td/select"));
			selenium.select("//div[17]/div/table/tbody/tr[19]/td/select", selenium.getEval("'" + FinlandFIovies + "'"));
			String FranceFRCNC = selenium.getEval("'-10'");
			verifyTrue(selenium.isElementPresent("//div[17]/div/table/tbody/tr[20]/td/select"));
			selenium.select("//div[17]/div/table/tbody/tr[20]/td/select", selenium.getEval("'" + FranceFRCNC + "'"));
			String GermanyDEFSK = selenium.getEval("'ab 12 Jahren'");
			verifyTrue(selenium.isElementPresent("//div[17]/div/table/tbody/tr[21]/td/select"));
			selenium.select("//div[17]/div/table/tbody/tr[21]/td/select", selenium.getEval("'" + GermanyDEFSK + "'"));
			String GreeceGRMovies = selenium.getEval("'K'");
			verifyTrue(selenium.isElementPresent("//div[17]/div/table/tbody/tr[22]/td/select"));
			selenium.select("//div[17]/div/table/tbody/tr[22]/td/select", selenium.getEval("'" + GreeceGRMovies + "'"));
			String GuatemalaGTMovies = selenium.getEval("'A'");
			verifyTrue(selenium.isElementPresent("//div[17]/div/table/tbody/tr[23]/td/select"));
			selenium.select("//div[17]/div/table/tbody/tr[23]/td/select", selenium.getEval("'" + GuatemalaGTMovies + "'"));
			String GuyanaGYMovies = selenium.getEval("'All Ages'");
			verifyTrue(selenium.isElementPresent("//div[17]/div/table/tbody/tr[24]/td/select"));
			selenium.select("//div[17]/div/table/tbody/tr[24]/td/select", selenium.getEval("'" + GuyanaGYMovies + "'"));
			String GuyanaGYMovies02 = selenium.getEval("'All Ages'");
			verifyTrue(selenium.isElementPresent("//div[17]/div/table/tbody/tr[24]/td/select"));
			selenium.select("//div[17]/div/table/tbody/tr[24]/td/select", selenium.getEval("'" + GuyanaGYMovies02 + "'"));
			String HungaryHUMovies = selenium.getEval("'12'");
			verifyTrue(selenium.isElementPresent("//div[17]/div/table/tbody/tr[26]/td/select"));
			selenium.select("//div[17]/div/table/tbody/tr[26]/td/select", selenium.getEval("'" + HungaryHUMovies + "'"));
			String IrelandIEIFCO = selenium.getEval("'12'");
			verifyTrue(selenium.isElementPresent("//div[17]/div/table/tbody/tr[27]/td/select"));
			selenium.select("//div[17]/div/table/tbody/tr[27]/td/select", selenium.getEval("'" + IrelandIEIFCO + "'"));
			String ItalyITMovies = selenium.getEval("'T'");
			verifyTrue(selenium.isElementPresent("//div[17]/div/table/tbody/tr[28]/td/select"));
			selenium.select("//div[17]/div/table/tbody/tr[28]/td/select", selenium.getEval("'" + ItalyITMovies + "'"));
			String JamaicaJMMovies = selenium.getEval("'U'");
			verifyTrue(selenium.isElementPresent("//div[17]/div/table[2]/tbody/tr/td/select"));
			selenium.select("//div[17]/div/table[2]/tbody/tr/td/select", selenium.getEval("'" + JamaicaJMMovies + "'"));
			String JapanJPEIRIN = selenium.getEval("'G'");
			verifyTrue(selenium.isElementPresent("//div[17]/div/table[2]/tbody/tr[2]/td/select"));
			selenium.select("//div[17]/div/table[2]/tbody/tr[2]/td/select", selenium.getEval("'" + JapanJPEIRIN + "'"));
			String LatviaLVMovies = selenium.getEval("'16+'");
			verifyTrue(selenium.isElementPresent("//div[17]/div/table[2]/tbody/tr[3]/td/select"));
			selenium.select("//div[17]/div/table[2]/tbody/tr[3]/td/select", selenium.getEval("'" + LatviaLVMovies + "'"));
			String LithuaniaLTMovies = selenium.getEval("'A'");
			verifyTrue(selenium.isElementPresent("//div[17]/div/table[2]/tbody/tr[4]/td/select"));
			selenium.select("//div[17]/div/table[2]/tbody/tr[4]/td/select", selenium.getEval("'" + LithuaniaLTMovies + "'"));
			String LuxembourgLUMovies = selenium.getEval("'12'");
			verifyTrue(selenium.isElementPresent("//div[17]/div/table[2]/tbody/tr[5]/td/select"));
			selenium.select("//div[17]/div/table[2]/tbody/tr[5]/td/select", selenium.getEval("'" + LuxembourgLUMovies + "'"));
			String MaltaMTMovies = selenium.getEval("'12'");
			verifyTrue(selenium.isElementPresent("//div[17]/div/table[2]/tbody/tr[6]/td/select"));
			selenium.select("//div[17]/div/table[2]/tbody/tr[6]/td/select", selenium.getEval("'" + MaltaMTMovies + "'"));
			String MexicoMXMovies = selenium.getEval("'A'");
			verifyTrue(selenium.isElementPresent("//div[17]/div/table[2]/tbody/tr[7]/td/select"));
			selenium.select("//div[17]/div/table[2]/tbody/tr[7]/td/select", selenium.getEval("'" + MexicoMXMovies + "'"));
			String NetherlandsNLMovies = selenium.getEval("'12'");
			verifyTrue(selenium.isElementPresent("//div[17]/div/table[2]/tbody/tr[8]/td/select"));
			selenium.select("//div[17]/div/table[2]/tbody/tr[8]/td/select", selenium.getEval("'" + NetherlandsNLMovies + "'"));
			String NewZealandNZOFLC = selenium.getEval("'G'");
			verifyTrue(selenium.isElementPresent("//div[17]/div/table[2]/tbody/tr[9]/td/select"));
			selenium.select("//div[17]/div/table[2]/tbody/tr[9]/td/select", selenium.getEval("'" + NewZealandNZOFLC + "'"));
			String NicaraguaNIMovies = selenium.getEval("'G'");
			verifyTrue(selenium.isElementPresent("//div[17]/div/table[2]/tbody/tr[9]/td/select"));
			selenium.select("//div[17]/div/table[2]/tbody/tr[9]/td/select", selenium.getEval("'" + NicaraguaNIMovies + "'"));
			String NorwayNOMovies = selenium.getEval("'PG'");
			verifyTrue(selenium.isElementPresent("//div[17]/div/table[2]/tbody/tr[10]/td/select"));
			selenium.select("//div[17]/div/table[2]/tbody/tr[10]/td/select", selenium.getEval("'" + NorwayNOMovies + "'"));
			String PanamaPAMovies = selenium.getEval("'11'");
			verifyTrue(selenium.isElementPresent("//div[17]/div/table[2]/tbody/tr[11]/td/select"));
			selenium.select("//div[17]/div/table[2]/tbody/tr[11]/td/select", selenium.getEval("'" + PanamaPAMovies + "'"));
			String ParaguayPYMovies = selenium.getEval("'A'");
			verifyTrue(selenium.isElementPresent("//div[17]/div/table[2]/tbody/tr[12]/td/select"));
			selenium.select("//div[17]/div/table[2]/tbody/tr[12]/td/select", selenium.getEval("'" + ParaguayPYMovies + "'"));
			String PeruPEMovies = selenium.getEval("'13'");
			verifyTrue(selenium.isElementPresent("//div[17]/div/table[2]/tbody/tr[13]/td/select"));
			selenium.select("//div[17]/div/table[2]/tbody/tr[13]/td/select", selenium.getEval("'" + PeruPEMovies + "'"));
			String PolandPlMovies = selenium.getEval("'14'");
			verifyTrue(selenium.isElementPresent("//div[17]/div/table[2]/tbody/tr[14]/td/select"));
			selenium.select("//div[17]/div/table[2]/tbody/tr[14]/td/select", selenium.getEval("'" + PolandPlMovies + "'"));
			String PortugalPTMovies = selenium.getEval("'12'");
			verifyTrue(selenium.isElementPresent("//div[17]/div/table[2]/tbody/tr[15]/td/select"));
			selenium.select("//div[17]/div/table[2]/tbody/tr[15]/td/select", selenium.getEval("'" + PortugalPTMovies + "'"));
			String QuebecCARCQ = selenium.getEval("'M/12'");
			verifyTrue(selenium.isElementPresent("//div[17]/div/table[2]/tbody/tr[16]/td/select"));
			selenium.select("//div[17]/div/table[2]/tbody/tr[16]/td/select", selenium.getEval("'" + QuebecCARCQ + "'"));
			String QuebecCARCQ02 = selenium.getEval("'13+'");
			verifyTrue(selenium.isElementPresent("//div[17]/div/table[2]/tbody/tr[17]/td/select"));
			selenium.select("//div[17]/div/table[2]/tbody/tr[17]/td/select", selenium.getEval("'" + QuebecCARCQ02 + "'"));
			String RomaniaROMovies = selenium.getEval("'A.G.'");
			verifyTrue(selenium.isElementPresent("//div[17]/div/table[2]/tbody/tr[18]/td/select"));
			selenium.select("//div[17]/div/table[2]/tbody/tr[18]/td/select", selenium.getEval("'" + RomaniaROMovies + "'"));
			String SlovakiaSKMovies = selenium.getEval("'12'");
			verifyTrue(selenium.isElementPresent("//div[17]/div/table[2]/tbody/tr[19]/td/select"));
			selenium.select("//div[17]/div/table[2]/tbody/tr[19]/td/select", selenium.getEval("'" + SlovakiaSKMovies + "'"));
			String SloveniaSIMovies = selenium.getEval("'+15'");
			verifyTrue(selenium.isElementPresent("//div[17]/div/table[2]/tbody/tr[20]/td/select"));
			selenium.select("//div[17]/div/table[2]/tbody/tr[20]/td/select", selenium.getEval("'" + SloveniaSIMovies + "'"));
			String SpainESMovies = selenium.getEval("'12'");
			verifyTrue(selenium.isElementPresent("//div[17]/div/table[2]/tbody/tr[21]/td/select"));
			selenium.select("//div[17]/div/table[2]/tbody/tr[21]/td/select", selenium.getEval("'" + SpainESMovies + "'"));
			String SurinameSRMovies = selenium.getEval("'All Ages'");
			verifyTrue(selenium.isElementPresent("//div[17]/div/table[2]/tbody/tr[22]/td/select"));
			selenium.select("//div[17]/div/table[2]/tbody/tr[22]/td/select", selenium.getEval("'" + SurinameSRMovies + "'"));
			String SwedenSEMovies = selenium.getEval("'Från 15 år'");
			verifyTrue(selenium.isElementPresent("//div[17]/div/table[2]/tbody/tr[23]/td/select"));
			selenium.select("//div[17]/div/table[2]/tbody/tr[23]/td/select", selenium.getEval("'" + SwedenSEMovies + "'"));
			String SwitzerlandCHMovies = selenium.getEval("'0'");
			verifyTrue(selenium.isElementPresent("//div[17]/div/table[2]/tbody/tr[24]/td/select"));
			selenium.select("//div[17]/div/table[2]/tbody/tr[24]/td/select", selenium.getEval("'" + SwitzerlandCHMovies + "'"));
			String UnitedKingdomBBFC = selenium.getEval("'12'");
			verifyTrue(selenium.isElementPresent("//div[17]/div/table[2]/tbody/tr[25]/td/select"));
			selenium.select("//div[17]/div/table[2]/tbody/tr[25]/td/select", selenium.getEval("'" + UnitedKingdomBBFC + "'"));
			String UruguayUYMovies = selenium.getEval("'+12'");
			verifyTrue(selenium.isElementPresent("//div[17]/div/table[2]/tbody/tr[26]/td/select"));
			selenium.select("//div[17]/div/table[2]/tbody/tr[26]/td/select", selenium.getEval("'" + UruguayUYMovies + "'"));
			String USMPAA = selenium.getEval("'G'");
			verifyTrue(selenium.isElementPresent("//div[17]/div/table[2]/tbody/tr[27]/td/select"));
			selenium.select("//div[17]/div/table[2]/tbody/tr[27]/td/select", selenium.getEval("'" + USMPAA + "'"));
			String VenezuelaVEMovies = selenium.getEval("'A'");
			verifyTrue(selenium.isElementPresent("//div[17]/div/table[2]/tbody/tr[28]/td/select"));
			selenium.select("//div[17]/div/table[2]/tbody/tr[28]/td/select", selenium.getEval("'" + VenezuelaVEMovies + "'"));
			System.out.println("Edit_Ex_Release End");

			System.out.println("Edit_Ex_Release Verification_Start");			
			verifyEquals(selenium.getValue("css=select[name=\"product_type_id\"]"), "3");
			verifyEquals(selenium.getValue("css=select[name=\"meta_language\"]"), "FRE");
			verifyEquals(selenium.getValue("css=input[name=\"release_name_req\"]"), selenium.getEval("'" + ReleaseName + "'"));
			verifyEquals(selenium.getValue("css=input[name=\"label\"]"), selenium.getEval("'" + LabelImprint + "'"));
			verifyEquals(selenium.getValue("css=input[name=\"manufacturer_upc\"]"), selenium.getEval("'" + ManufacturersUPC + "'"));
			verifyEquals(selenium.getValue("css=input[name=\"c_line\"]"), selenium.getEval("'" + Line + "'"));
			verifyEquals(selenium.getValue("css=textarea[name=\"description\"]"), selenium.getEval("'" + DescriptionSynopsis + "'"));
			verifyEquals(selenium.getValue("css=select[name=\"not_for_distribution\"]"), selenium.getEval("'" + NotForDistribution + "'"));
			verifyEquals(selenium.getValue("css=select[name=\"unknown_artist\"]"), selenium.getEval("'" + TributeByUnknownArtist + "'"));
			verifyEquals(selenium.getValue("css=input[name=\"promo_upc\"]"), selenium.getEval("'" + PromoUPC + "'"));
			verifyEquals(selenium.getValue("css=select[name=\"language_id\"]"), selenium.getEval("'" + Language + "'"));
			verifyEquals(selenium.getValue("css=select[name=\"subtitle_language_id\"]"), "FRE");
			verifyEquals(selenium.getValue("css=select[name=\"priority\"]"), selenium.getEval("'" + InitialPriority + "'"));
			verifyEquals(selenium.getValue("css=select[name=\"new_release\"]"), "Direct_To_Video");
			verifyEquals(selenium.getValue("css=select[name=\"prmPreorderType\"]"), selenium.getEval("'" + PreOrderDate + "'"));
			verifyEquals(selenium.getValue("css=select[name=\"prmArtistID\"]"), "167218");
			verifyEquals(selenium.getValue("css=input[name=\"release_date\"]"), selenium.getEval("'" + ReleaseDate + "'"));
			verifyEquals(selenium.getValue("css=input[name=\"sale_start_date\"]"), selenium.getEval("'" + SaleStartDate + "'"));
			verifyEquals(selenium.getValue("css=input[name=\"vod_start_date\"]"), selenium.getEval("'" + SaleStartDate + "'"));
			verifyEquals(selenium.getValue("css=input[name=\"VCN\"]"), selenium.getEval("'" + LabelCatalog + "'"));
			verifyEquals(selenium.getValue("css=select[name=\"distribution\"]"), selenium.getEval("'" + Distribution + "'"));
			verifyEquals(selenium.getValue("css=#primary_genre_id"), "3");
			verifyEquals(selenium.getValue("css=input[name=\"promos_number\"]"), selenium.getEval("'" + ofPromos + "'"));
			verifyEquals(selenium.getValue("css=select[name=\"europe_public_domain\"]"), selenium.getEval("'" + PublicDomaininEurope + "'"));
			verifyEquals(selenium.getValue("css=select[name=\"product_format\"]"), selenium.getEval("'" + ProductFormat + "'"));
			verifyEquals(selenium.getValue("css=#format"), selenium.getEval("'" + Format + "'"));
			verifyEquals(selenium.getValue("css=select[name=\"karaoke\"]"), selenium.getEval("'" + Karaoke + "'"));
			verifyEquals(selenium.getValue("css=select[name=\"digital_only\"]"), selenium.getEval("'" + DigitalOnly + "'"));
			verifyEquals(selenium.getValue("css=input[name=\"version\"]"), selenium.getEval("'" + Version + "'"));
			verifyEquals(selenium.getValue("name=short_synopsis_film"), selenium.getEval("'" + ShortSynopsis + "'"));
			verifyEquals(selenium.getValue("css=input[name=\"amd_id_film\"]"), selenium.getEval("'" + AMGID + "'"));
			verifyEquals(selenium.getValue("css=input[name=\"theatrical_release_date_film\"]"), selenium.getEval("'" + TheatricalReleaseDate + "'"));
			verifyEquals(selenium.getValue("css=input[name=\"physical_release_date\"]"), selenium.getEval("'" + PhysicalReleaseDate + "'"));
			verifyEquals(selenium.getValue("css=select[name=\"film_subtype_film\"]"), "2");
			verifyEquals(selenium.getValue("css=select[name=\"country_of_origin_film\"]"), "21");
			verifyEquals(selenium.getValue("css=select[name=\"channel_id_film\"]"), "20");
			verifyEquals(selenium.getValue("css=input[name=\"production_co_film\"]"), selenium.getEval("'" + ProductionCo + "'"));
			verifyEquals(selenium.getValue("css=input[name=\"brand_film\"]"), selenium.getEval("'" + Brand + "'"));
			verifyEquals(selenium.getValue("css=input[name=\"tms_id_film\"]"), selenium.getEval("'" + TMSMovieID + "'"));
			verifyEquals(selenium.getValue("css=input[name=\"reasons_film[ar_movies]\"]"), selenium.getEval("'" + ARMovies + "'"));
			verifyEquals(selenium.getValue("css=input[name=\"reasons_film[au_oflc]\"]"), selenium.getEval("'" + AUOFLC + "'"));
			verifyEquals(selenium.getValue("css=input[name=\"reasons_film[fsk]\"]"), selenium.getEval("'" + FSK + "'"));
			verifyEquals(selenium.getValue("css=input[name=\"reasons_film[be_movies]\"]"), selenium.getEval("'" + BEMovies + "'"));
			verifyEquals(selenium.getValue("css=input[name=\"reasons_film[bo_movies]\"]"), selenium.getEval("'" + BOMovies + "'"));
			verifyEquals(selenium.getValue("css=input[name=\"reasons_film[br_movies]\"]"), selenium.getEval("'" + BRMovies + "'"));
			verifyEquals(selenium.getValue("css=input[name=\"reasons_film[bg_movies]\"]"), selenium.getEval("'" + BGMovies + "'"));
			verifyEquals(selenium.getValue("css=input[name=\"reasons_film[ca_chvrs]\"]"), selenium.getEval("'" + CACHVRS + "'"));
			verifyEquals(selenium.getValue("css=input[name=\"reasons_film[cl_movies]\"]"), selenium.getEval("'" + CLMovies + "'"));
			verifyEquals(selenium.getValue("css=input[name=\"reasons_film[co_movies]\"]"), selenium.getEval("'" + COMovies + "'"));
			verifyEquals(selenium.getValue("css=input[name=\"reasons_film[cr_movies]\"]"), selenium.getEval("'" + CRMovies + "'"));
			verifyEquals(selenium.getValue("css=input[name=\"reasons_film[cy_movies]\"]"), selenium.getEval("'" + CYMovies + "'"));
			verifyEquals(selenium.getValue("css=input[name=\"reasons_film[cz_movies]\"]"), selenium.getEval("'" + CZMovies + "'"));
			verifyEquals(selenium.getValue("css=input[name=\"reasons_film[dk_movies]\"]"), selenium.getEval("'" + DKMovies + "'"));
			verifyEquals(selenium.getValue("css=input[name=\"reasons_film[do_movies]\"]"), selenium.getEval("'" + DOMovies + "'"));
			verifyEquals(selenium.getValue("css=input[name=\"reasons_film[ec_movies]\"]"), selenium.getEval("'" + ECMovies + "'"));
			verifyEquals(selenium.getValue("css=input[name=\"reasons_film[sv_movies]\"]"), selenium.getEval("'" + SVMovies + "'"));
			verifyEquals(selenium.getValue("css=input[name=\"reasons_film[ee_movies]\"]"), selenium.getEval("'" + EEMovies + "'"));
			verifyEquals(selenium.getValue("css=input[name=\"reasons_film[fi_movies]\"]"), selenium.getEval("'" + FIMovies + "'"));
			verifyEquals(selenium.getValue("css=input[name=\"reasons_film[fr_cnc]\"]"), selenium.getEval("'" + FRMovies + "'"));
			verifyEquals(selenium.getValue("css=input[name=\"reasons_film[de-fsk]\"]"), selenium.getEval("'" + DEFSK + "'"));
			verifyEquals(selenium.getValue("css=input[name=\"reasons_film[gr_movies]\"]"), selenium.getEval("'" + GRMovies + "'"));
			verifyEquals(selenium.getValue("css=input[name=\"reasons_film[gt_movies]\"]"), selenium.getEval("'" + GTMovies + "'"));
			verifyEquals(selenium.getValue("css=input[name=\"reasons_film[gy_movies]\"]"), selenium.getEval("'" + GYMovies + "'"));
			verifyEquals(selenium.getValue("css=input[name=\"reasons_film[hn_movies]\"]"), selenium.getEval("'" + HNMovies + "'"));
			verifyEquals(selenium.getValue("css=input[name=\"reasons_film[hu_movies]\"]"), selenium.getEval("'" + HUMovies + "'"));
			verifyEquals(selenium.getValue("css=input[name=\"reasons_film[ie_ifco]\"]"), selenium.getEval("'" + IEIfco + "'"));
			verifyEquals(selenium.getValue("css=input[name=\"reasons_film[it_movies]\"]"), selenium.getEval("'" + ITMovies + "'"));
			verifyEquals(selenium.getValue("css=input[name=\"reasons_film[jm_movies]\"]"), selenium.getEval("'" + JMMovies + "'"));
			verifyEquals(selenium.getValue("css=input[name=\"reasons_film[jp_eirin]\"]"), selenium.getEval("'" + JPEIRIN + "'"));
			verifyEquals(selenium.getValue("css=input[name=\"reasons_film[lv_movies]\"]"), selenium.getEval("'" + LVMovies + "'"));
			verifyEquals(selenium.getValue("css=input[name=\"reasons_film[lt_movies]\"]"), selenium.getEval("'" + LTMovies + "'"));
			verifyEquals(selenium.getValue("css=input[name=\"reasons_film[lu_movies]\"]"), selenium.getEval("'" + LUMovies + "'"));
			verifyEquals(selenium.getValue("css=input[name=\"reasons_film[mt_movies]\"]"), selenium.getEval("'" + MTMovies + "'"));
			verifyEquals(selenium.getValue("css=input[name=\"reasons_film[mx_movies]\"]"), selenium.getEval("'" + MXMovies + "'"));
			verifyEquals(selenium.getValue("css=input[name=\"reasons_film[nl_movies]\"]"), selenium.getEval("'" + NLMovies + "'"));
			verifyEquals(selenium.getValue("css=input[name=\"reasons_film[nz_oflc]\"]"), selenium.getEval("'" + NZOflc + "'"));
			verifyEquals(selenium.getValue("css=input[name=\"reasons_film[ni_movies]\"]"), selenium.getEval("'" + NIMovies + "'"));
			verifyEquals(selenium.getValue("css=input[name=\"reasons_film[no_movies]\"]"), selenium.getEval("'" + NOMovies + "'"));
			verifyEquals(selenium.getValue("css=input[name=\"reasons_film[pa_movies]\"]"), selenium.getEval("'" + PAMovies + "'"));
			verifyEquals(selenium.getValue("css=input[name=\"reasons_film[py_movies]\"]"), selenium.getEval("'" + PYMovies + "'"));
			verifyEquals(selenium.getValue("css=input[name=\"reasons_film[pe_movies]\"]"), selenium.getEval("'" + PEMovies + "'"));
			verifyEquals(selenium.getValue("css=input[name=\"reasons_film[pl_movies]\"]"), selenium.getEval("'" + PLMovies + "'"));
			verifyEquals(selenium.getValue("css=input[name=\"reasons_film[pt_movies]\"]"), selenium.getEval("'" + PTMovies + "'"));
			verifyEquals(selenium.getValue("css=input[name=\"reasons_film[ca-rcq]\"]"), selenium.getEval("'" + CARcq + "'"));
			verifyEquals(selenium.getValue("css=input[name=\"reasons_film[ro_movies]\"]"), selenium.getEval("'" + ROMovies + "'"));
			verifyEquals(selenium.getValue("css=input[name=\"reasons_film[sk_movies]\"]"), selenium.getEval("'" + SKMovies + "'"));
			verifyEquals(selenium.getValue("css=input[name=\"reasons_film[si_movies]\"]"), selenium.getEval("'" + SIMovies + "'"));
			verifyEquals(selenium.getValue("css=input[name=\"reasons_film[es_movies]\"]"), selenium.getEval("'" + ESMovies + "'"));
			verifyEquals(selenium.getValue("css=input[name=\"reasons_film[sr_movies]\"]"), selenium.getEval("'" + SRMovies + "'"));
			verifyEquals(selenium.getValue("css=input[name=\"reasons_film[ch_movies]\"]"), selenium.getEval("'" + CHMovies + "'"));
			verifyEquals(selenium.getValue("css=input[name=\"reasons_film[se_movies]\"]"), selenium.getEval("'" + SEMovies + "'"));
			verifyEquals(selenium.getValue("css=input[name=\"reasons_film[bbfc]\"]"), selenium.getEval("'" + BBFC + "'"));
			verifyEquals(selenium.getValue("css=input[name=\"reasons_film[uy_movies]\"]"), selenium.getEval("'" + UYMovies + "'"));
			verifyEquals(selenium.getValue("css=input[name=\"reasons_film[mpaa]\"]"), selenium.getEval("'" + MPAA + "'"));
			verifyEquals(selenium.getValue("css=input[name=\"reasons_film[ve_movies]\"]"), selenium.getEval("'" + VEMovies + "'"));
			verifyEquals(selenium.getValue("//div[17]/div/table/tbody/tr/td/select"), "111");
			verifyEquals(selenium.getValue("//div[17]/div/table/tbody/tr[2]/td/select"), "74");
			verifyEquals(selenium.getValue("//div[17]/div/table/tbody/tr[3]/td/select"), "121");
			verifyEquals(selenium.getValue("//div[17]/div/table/tbody/tr[4]/td/select"), "130");
			verifyEquals(selenium.getValue("//div[17]/div/table/tbody/tr[5]/td/select"), "146");
			verifyEquals(selenium.getValue("//div[17]/div/table/tbody/tr[6]/td/select"), "150");
			verifyEquals(selenium.getValue("//div[17]/div/table/tbody/tr[7]/td/select"), "155");
			verifyEquals(selenium.getValue("//div[17]/div/table/tbody/tr[8]/td/select"), "82");
			verifyEquals(selenium.getValue("//div[17]/div/table/tbody/tr[9]/td/select"), "162");
			verifyEquals(selenium.getValue("//div[17]/div/table/tbody/tr[10]/td/select"), "167");
			verifyEquals(selenium.getValue("//div[17]/div/table/tbody/tr[11]/td/select"), "172");
			verifyEquals(selenium.getValue("//div[17]/div/table/tbody/tr[12]/td/select"), "177");
			verifyEquals(selenium.getValue("//div[17]/div/table/tbody/tr[13]/td/select"), "181");
			verifyEquals(selenium.getValue("//div[17]/div/table/tbody/tr[14]/td/select"), "186");
			verifyEquals(selenium.getValue("//div[17]/div/table/tbody/tr[15]/td/select"), "188");
			verifyEquals(selenium.getValue("//div[17]/div/table/tbody/tr[16]/td/select"), "191");
			verifyEquals(selenium.getValue("//div[17]/div/table/tbody/tr[17]/td/select"), "197");
			verifyEquals(selenium.getValue("//div[17]/div/table/tbody/tr[18]/td/select"), "204");
			verifyEquals(selenium.getValue("//div[17]/div/table/tbody/tr[19]/td/select"), "209");
			verifyEquals(selenium.getValue("//div[17]/div/table/tbody/tr[20]/td/select"), "92");
			verifyEquals(selenium.getValue("//div[17]/div/table/tbody/tr[21]/td/select"), "89");
			verifyEquals(selenium.getValue("//div[17]/div/table/tbody/tr[22]/td/select"), "218");
			verifyEquals(selenium.getValue("//div[17]/div/table/tbody/tr[23]/td/select"), "221");
			verifyEquals(selenium.getValue("//div[17]/div/table/tbody/tr[24]/td/select"), "227");
			verifyEquals(selenium.getValue("//div[17]/div/table/tbody/tr[26]/td/select"), "235");
			verifyEquals(selenium.getValue("//div[17]/div/table/tbody/tr[27]/td/select"), "240");
			verifyEquals(selenium.getValue("//div[17]/div/table/tbody/tr[28]/td/select"), "243");
			verifyEquals(selenium.getValue("//div[17]/div/table[2]/tbody/tr/td/select"), "249");
			verifyEquals(selenium.getValue("//div[17]/div/table[2]/tbody/tr[2]/td/select"), "96");
			verifyEquals(selenium.getValue("//div[17]/div/table[2]/tbody/tr[3]/td/select"), "259");
			verifyEquals(selenium.getValue("//div[17]/div/table[2]/tbody/tr[4]/td/select"), "261");
			verifyEquals(selenium.getValue("//div[17]/div/table[2]/tbody/tr[5]/td/select"), "142");
			verifyEquals(selenium.getValue("//div[17]/div/table[2]/tbody/tr[6]/td/select"), "268");
			verifyEquals(selenium.getValue("//div[17]/div/table[2]/tbody/tr[7]/td/select"), "273");
			verifyEquals(selenium.getValue("//div[17]/div/table[2]/tbody/tr[8]/td/select"), "136");
			verifyEquals(selenium.getValue("//div[17]/div/table[2]/tbody/tr[9]/td/select"), "101");
			verifyEquals(selenium.getValue("//div[17]/div/table[2]/tbody/tr[10]/td/select"), "278");
			verifyEquals(selenium.getValue("//div[17]/div/table[2]/tbody/tr[11]/td/select"), "284");
			verifyEquals(selenium.getValue("//div[17]/div/table[2]/tbody/tr[12]/td/select"), "288");
			verifyEquals(selenium.getValue("//div[17]/div/table[2]/tbody/tr[13]/td/select"), "294");
			verifyEquals(selenium.getValue("//div[17]/div/table[2]/tbody/tr[14]/td/select"), "299");
			verifyEquals(selenium.getValue("//div[17]/div/table[2]/tbody/tr[15]/td/select"), "304");
			verifyEquals(selenium.getValue("//div[17]/div/table[2]/tbody/tr[16]/td/select"), "310");
			verifyEquals(selenium.getValue("//div[17]/div/table[2]/tbody/tr[17]/td/select"), "316");
			verifyEquals(selenium.getValue("//div[17]/div/table[2]/tbody/tr[18]/td/select"), "320");
			verifyEquals(selenium.getValue("//div[17]/div/table[2]/tbody/tr[19]/td/select"), "326");
			verifyEquals(selenium.getValue("//div[17]/div/table[2]/tbody/tr[20]/td/select"), "329");
			verifyEquals(selenium.getValue("//div[17]/div/table[2]/tbody/tr[21]/td/select"), "335");
			verifyEquals(selenium.getValue("//div[17]/div/table[2]/tbody/tr[22]/td/select"), "340");
			verifyEquals(selenium.getValue("//div[17]/div/table[2]/tbody/tr[23]/td/select"), "345");
			verifyEquals(selenium.getValue("//div[17]/div/table[2]/tbody/tr[24]/td/select"), "347");
			verifyEquals(selenium.getValue("//div[17]/div/table[2]/tbody/tr[25]/td/select"), "13");
			verifyEquals(selenium.getValue("//div[17]/div/table[2]/tbody/tr[26]/td/select"), "359");
			verifyEquals(selenium.getValue("//div[17]/div/table[2]/tbody/tr[27]/td/select"), "369");
			verifyEquals(selenium.getValue("//div[17]/div/table[2]/tbody/tr[28]/td/select"), "364");
			
		    //Logout
			Thread.sleep(8000);
			selenium.clickAt("link=Logout", "");
			Thread.sleep(5000);
			for (int second1 = 0;; second1++) {
				if (second1 >= 60) fail("timeout");
				try { if (selenium.isElementPresent("id=loginBox")) break; } catch (Exception e) {}
				Thread.sleep(1000);}
		}
	}
		@AfterClass
	    public void afterClass() {
			try {
				Common.CtearDown(selenium);
			} catch (Exception e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
	    }
	
}
